import { ToolDefinition } from "@/types";

export const tools: ToolDefinition[] = [
  // ==========================================
  // Category 1: Organization (10 Tools)
  // ==========================================
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one unified document.",
    category: "Organization",
    href: "/merge-pdf",
    icon: "Combine",
    status: "implemented",
    seoTitle: "Merge PDF Files Online Free (No Limits)",
    seoDescription: "Combine multiple PDF files into one document in seconds. 100% free, unlimited file size, and runs privately in your browser with zero server uploads.",
    keywords: ["merge pdf", "merge pdf files", "combine pdf", "join pdf files", "merge pdf online free", "pdf merger without upload"],
    seoH1: "Merge PDF Files Online Free",
    seoH2s: ["How to Merge PDF Files Online", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Combine multiple PDF documents, reports, presentations, and scans into a single organized PDF file in seconds. KissThePDF provides a blazingly fast, browser-native PDF merger that eliminates the frustrating file size limits, hourly usage quotas, and cloud privacy vulnerabilities found on traditional PDF websites. Simply drag and drop your files into the upload area, arrange the document cards into your preferred sequence using intuitive drag-and-drop controls, and click Merge to generate a unified document instantly. Because our merging engine is powered by client-side WebAssembly, all document processing executes 100% locally on your computer hardware. Your confidential legal contracts, financial audits, medical records, and personal identification documents never leave your machine or get stored on remote servers. Merge large documents with unlimited pages, zero watermarks, no account requirements, and complete data privacy. Perfect for combining monthly bank statements, legal annexes, research papers, and multi-part project documentation into a single polished PDF file.",
    howTo: {
      name: "How to Merge Multiple PDF Files",
      description: "Combine two or more PDF files into a single document in 3 quick steps.",
      steps: [
        { name: "Add PDF Files", text: "Click Select PDF files or drag and drop all the files you want to combine into the upload zone." },
        { name: "Reorder Documents", text: "Drag the file cards up or down to set the exact sequence for your combined PDF." },
        { name: "Merge and Download", text: "Click Merge PDF to instantly join the documents and download your unified file." },
      ]
    },
    faqs: [
      { question: "Is there a file size or page limit when merging PDFs?", answer: "No. KissThePDF has no artificial file size or page count limits. You can combine large documents directly in your browser." },
      { question: "Can I merge images along with PDF files?", answer: "Yes. Use our Images to PDF or Photo Album tools to convert images to PDF first, or merge them directly." },
      { question: "Will bookmarks and interactive links be preserved?", answer: "Standard page content, bookmarks, and internal links from the original documents are preserved during the merge process." },
      { question: "Can I merge password-protected PDF files?", answer: "If a PDF has an open password, unlock it first using our Decrypt PDF tool before merging." },
      { question: "Are my merged PDF files uploaded to any server?", answer: "No. All processing happens 100% locally inside your web browser. Your confidential data never leaves your device." },
    ],
    relatedTools: ["split-pdf", "organize-pdf", "reorder-pages", "compress-pdf", "images-to-pdf"],
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Separate pages or page ranges from a PDF into independent files.",
    category: "Organization",
    href: "/split-pdf",
    icon: "SplitSquareHorizontal",
    status: "implemented",
    seoTitle: "Split PDF Pages Online Free",
    seoDescription: "Split PDF documents into individual pages or custom page ranges. Fast, free, and processed 100% locally in your browser with no upload limits.",
    keywords: ["split pdf", "split pdf pages", "extract pages from pdf", "separate pdf", "split pdf online free", "cut pdf into pieces"],
    seoH1: "Split PDF Pages Online Free",
    seoH2s: ["How to Split PDF Pages Online", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Separate large PDF files into individual single-page documents or extract specific custom page ranges effortlessly with our free online PDF splitter. KissThePDF gives you full granular control over your documents: extract specific page ranges (such as pages 1-5, 8, and 12-16), split every single page into an independent PDF, or separate odd and even pages for dual-sided scanning workflows. The splitting engine extracts original binary page structures directly, preserving vector text fonts, hyperlinks, high-resolution graphics, and bookmark hierarchies without recompression quality loss. Because all document division runs 100% locally in your browser sandbox, you can process 100MB+ files instantaneously without waiting for slow cloud uploads or bandwidth throttling. Enjoy unrestricted PDF splitting with complete data confidentiality, zero watermarks, and no sign-up or email requirements. Download extracted excerpts or packaged ZIP archives containing your split files in seconds, completely free and private. Our intuitive thumbnail interface lets you review page numbers before confirming your split selection.",
    howTo: {
      name: "How to Split a PDF into Separate Files",
      description: "Extract pages or divide a PDF into multiple documents in 3 steps.",
      steps: [
        { name: "Upload PDF", text: "Drag and drop your PDF document into the Split PDF tool." },
        { name: "Set Split Ranges", text: "Specify custom page ranges (e.g. 1-3, 5, 7-10) or choose to split every page separately." },
        { name: "Split and Download", text: "Click Split PDF to download your separated pages as individual files or a packaged ZIP." },
      ]
    },
    faqs: [
      { question: "How do I format custom page ranges?", answer: "Use commas and hyphens to define ranges (e.g. 1-4, 7, 9-12). You can extract single pages or multiple distinct sections at once." },
      { question: "Can I split every page into its own separate PDF?", answer: "Yes. Choose the 'Split all pages' option to export every single page as an individual numbered PDF document." },
      { question: "Does splitting a PDF reduce document quality?", answer: "No. The split tool extracts the exact binary page structures, preserving all vector text, high-resolution images, and formatting." },
      { question: "Can I split large PDF files without uploading?", answer: "Yes. Because KissThePDF processes files locally on your computer, you can split 100MB+ documents without waiting for upload or download transfers." },
      { question: "Is my document data kept private?", answer: "Yes. KissThePDF never transmits your files to any remote server. Everything happens inside your local browser sandbox." },
    ],
    relatedTools: ["merge-pdf", "extract-pdf-pages", "delete-pdf-pages", "duplicate-pages", "organize-pdf"],
  },
  {
    id: "extract-pdf-pages",
    name: "Extract Pages",
    description: "Create a new PDF containing only selected pages.",
    category: "Organization",
    href: "/extract-pdf-pages",
    icon: "FileOutput",
    status: "implemented",
    seoTitle: "Extract Pages from PDF Online",
    seoDescription: "Extract selected pages from a PDF into a new document directly in your browser.",
    keywords: ["extract pdf pages", "extract pages from pdf", "pull pages from pdf"],
  },
  {
    id: "delete-pdf-pages",
    name: "Delete Pages",
    description: "Remove unwanted pages from your PDF securely.",
    category: "Organization",
    href: "/delete-pdf-pages",
    icon: "Trash2",
    status: "implemented",
    seoTitle: "Delete PDF Pages Online for Free",
    seoDescription: "Easily select and remove specific pages from your PDF document without server upload.",
    keywords: ["delete pdf pages", "remove pdf pages", "delete page from pdf"],
  },
  {
    id: "reorder-pages",
    name: "Reorder Pages",
    description: "Rearrange PDF pages into any custom sequence.",
    category: "Organization",
    href: "/reorder-pages",
    icon: "ArrowUpDown",
    status: "implemented",
    seoTitle: "Reorder PDF Pages Free Online",
    seoDescription: "Rearrange page order in any PDF with simple visual drag and drop.",
    keywords: ["reorder pdf pages", "rearrange pdf", "sort pdf pages"],
  },
  {
    id: "duplicate-pages",
    name: "Duplicate Pages",
    description: "Duplicate selected pages within a PDF document.",
    category: "Organization",
    href: "/duplicate-pages",
    icon: "Copy",
    status: "implemented",
    seoTitle: "Duplicate PDF Pages Online Free",
    seoDescription: "Duplicate and clone specific pages within any PDF document. Free browser tool to copy single or multiple pages instantly without uploading files.",
    keywords: ["pdf page duplicator", "duplicate pages in pdf", "duplicate pdf pages", "clone pdf page", "copy pdf pages", "replicate pdf page"],
    seoH1: "Duplicate PDF Pages Online Free",
    seoH2s: ["How to Duplicate Pages in a PDF", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Duplicate and clone individual pages or full page ranges within any PDF document using our fast, visual page duplication tool. Perfect for creating multiple copies of invoice templates, recurring contract sheets, blank certificates, survey questionnaires, or presentation handouts without manually copying and merging files. KissThePDF presents a visual thumbnail grid of your document where you can select specific target pages and choose the exact number of duplicate copies to insert. Duplicated pages retain their original vector typography, embedded fonts, image resolutions, and layout fidelity through direct binary page cloning. Because the document restructuring executes 100% locally in your web browser using client-side JavaScript, even large multi-megabyte PDFs are processed in milliseconds without waiting for server uploads or downloads. Enjoy unlimited page duplication with complete data privacy, zero watermarks, and no sign-up requirements. Easily reorder, delete, or organize your cloned pages before exporting a perfectly structured final document for work or print.",
    howTo: {
      name: "How to Duplicate Pages in a PDF",
      description: "Easily clone one or more pages in your PDF document in 3 steps.",
      steps: [
        { name: "Select Your PDF", text: "Upload or drag your PDF into the Duplicate Pages tool." },
        { name: "Choose Pages to Duplicate", text: "Select the page thumbnail(s) you want to copy and specify how many duplicates to insert." },
        { name: "Generate and Download", text: "Click Duplicate Pages to instantly generate and download your updated PDF." },
      ]
    },
    faqs: [
      { question: "Where are the duplicated pages placed in the PDF?", answer: "By default, duplicated pages are placed immediately after the original page in the document sequence." },
      { question: "Can I duplicate multiple different pages at the same time?", answer: "Yes. You can select multiple individual pages or ranges across your document and duplicate them in a single operation." },
      { question: "Does duplicating pages degrade image or text quality?", answer: "No. Pages are copied as exact binary clones within the PDF structure, preserving original vector text, fonts, and image resolutions." },
      { question: "Can I reorder or delete pages after duplicating?", answer: "Yes. You can use our Reorder Pages or Organize PDF tools to arrange the pages into any custom sequence." },
      { question: "Are my files uploaded to a remote server?", answer: "No. KissThePDF operates 100% locally in your browser. Your documents never leave your computer." },
    ],
    relatedTools: ["organize-pdf", "reorder-pages", "extract-pdf-pages", "delete-pdf-pages", "split-pdf", "merge-pdf"],
  },
  {
    id: "insert-blank-page",
    name: "Insert Blank Page",
    description: "Insert a clean blank page anywhere inside a PDF document.",
    category: "Organization",
    href: "/insert-blank-page",
    icon: "FilePlus",
    status: "implemented",
    seoTitle: "Insert Blank Page into PDF",
    seoDescription: "Add blank pages to your PDF document at specific page positions.",
    keywords: ["insert blank page pdf", "add empty page to pdf"],
  },
  {
    id: "insert-pdf-pages",
    name: "Insert PDF Pages",
    description: "Insert pages from another PDF into your document.",
    category: "Organization",
    href: "/insert-pdf-pages",
    icon: "FileInput",
    status: "implemented",
    seoTitle: "Insert PDF Pages Online",
    seoDescription: "Combine pages from external PDFs directly into target page positions.",
    keywords: ["insert pages into pdf", "add pages from pdf"],
  },
  {
    id: "move-pages-between-pdfs",
    name: "Move Pages Between PDFs",
    description: "Select and transfer pages between multiple PDF documents.",
    category: "Organization",
    href: "/move-pages-between-pdfs",
    icon: "ArrowLeftRight",
    status: "implemented",
    seoTitle: "Move Pages Between PDFs",
    seoDescription: "Transfer selected pages interactively between multiple PDF files.",
    keywords: ["move pages between pdfs", "transfer pdf pages"],
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    description: "Complete page manager to reorder, delete, rotate, and duplicate pages.",
    category: "Organization",
    href: "/organize-pdf",
    icon: "LayoutGrid",
    status: "implemented",
    seoTitle: "Organize PDF Pages Free",
    seoDescription: "All-in-one visual page manager to rearrange, rotate, duplicate, and delete PDF pages.",
    keywords: ["organize pdf", "manage pdf pages"],
  },

  // ==========================================
  // Category 2: Pages (20 Tools)
  // ==========================================
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate individual PDF pages or the entire document.",
    category: "Pages",
    href: "/rotate-pdf",
    icon: "RotateCw",
    status: "implemented",
    seoTitle: "Rotate PDF Pages Online",
    seoDescription: "Rotate individual PDF pages or the entire document with visual page previews.",
    keywords: ["rotate pdf", "turn pdf", "change pdf orientation"],
  },
  {
    id: "rotate-entire-pdf",
    name: "Rotate Entire PDF",
    description: "Rotate every page in a PDF document by 90°, 180°, or 270°.",
    category: "Pages",
    href: "/rotate-entire-pdf",
    icon: "RotateCcw",
    status: "implemented",
    seoTitle: "Rotate Entire PDF Document",
    seoDescription: "Batch rotate all pages in your PDF document simultaneously.",
    keywords: ["rotate all pdf pages", "rotate document"],
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    description: "Crop margins or specific rectangular areas from PDF pages.",
    category: "Pages",
    href: "/crop-pdf",
    icon: "Crop",
    status: "implemented",
    seoTitle: "Crop PDF Pages Online Free",
    seoDescription: "Crop and trim PDF margins online. Adjust page dimensions visually for single pages or all pages. Free, private, and runs locally in your browser.",
    keywords: ["crop pdf pages", "crop pdf", "trim pdf margins", "crop pdf online", "crop pdf free", "cut pdf margins"],
    seoH1: "Crop PDF Pages Online Free",
    seoH2s: ["How to Crop PDF Pages Online", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Crop PDF margins, trim unwanted whitespace, remove cluttered headers and footers, and resize page dimensions visually with our free online PDF cropping tool. KissThePDF features an interactive visual crop overlay that allows you to drag bounding box handles across any page to isolate exact document regions or apply uniform crop dimensions across all pages simultaneously. Ideal for optimizing scanned book pages, preparing documents for booklet printing, reformatting charts for mobile e-readers, or extracting specific table sections. Our cropping engine modifies the standard PDF CropBox and MediaBox attributes without degrading vector text sharpness or image resolutions. Because all cropping calculations and document exports run 100% locally in your browser memory, your confidential business reports, legal filings, and personal documents never touch an external server. Trim your PDFs with precision, speed, and absolute privacy\u2014completely free with no watermarks or file size caps. Export clean, trimmed PDFs ready for professional presentations, academic submissions, and mobile reading.",
    howTo: {
      name: "How to Crop PDF Pages Online",
      description: "Visually crop margins and trim PDF pages in 3 simple steps.",
      steps: [
        { name: "Upload PDF File", text: "Drop your PDF document into the Crop PDF tool." },
        { name: "Adjust Crop Boundary", text: "Drag the interactive crop handles on the preview canvas to define your desired page area." },
        { name: "Apply and Download", text: "Choose whether to crop the current page or all pages, then click Crop PDF to download." },
      ]
    },
    faqs: [
      { question: "Can I apply the same crop area to all pages at once?", answer: "Yes. You can choose to apply the crop boundary to just the active page, all pages, or only odd/even pages." },
      { question: "Does cropping reduce the overall PDF file size?", answer: "Cropping adjusts the visible page viewport (CropBox/MediaBox). To further compress images and remove hidden metadata, combine cropping with our Compress PDF tool." },
      { question: "Can I crop to standard document sizes like A4 or Letter?", answer: "Yes. You can adjust the crop box freely or use our dedicated A4 PDF and Scale PDF tools for fixed standard page dimensions." },
      { question: "Is the original document content preserved if I need to re-crop?", answer: "Yes. You can always re-upload your original file or adjust crop boxes before downloading." },
      { question: "Are my documents secure during cropping?", answer: "Yes. KissThePDF processes your files entirely inside your browser. No files are ever sent to any external server." },
    ],
    relatedTools: ["add-margins", "scale-pdf", "a4-pdf", "rotate-pdf", "split-pdf"],
  },
  {
    id: "resize-pdf",
    name: "Resize PDF",
    description: "Change PDF page dimensions to standard or custom sizes.",
    category: "Pages",
    href: "/resize-pdf",
    icon: "Maximize2",
    status: "implemented",
    seoTitle: "Resize PDF Page Dimensions",
    seoDescription: "Resize PDF page dimensions to standard formats or custom width/height.",
    keywords: ["resize pdf", "change pdf page size"],
  },
  {
    id: "change-page-orientation",
    name: "Change Page Orientation",
    description: "Convert pages between Portrait and Landscape orientations.",
    category: "Pages",
    href: "/change-page-orientation",
    icon: "Smartphone",
    status: "implemented",
    seoTitle: "Change PDF Page Orientation",
    seoDescription: "Toggle PDF pages between landscape and portrait orientation.",
    keywords: ["pdf landscape to portrait", "change page orientation"],
  },
  {
    id: "change-page-size",
    name: "Change Page Size",
    description: "Adjust PDF pages to standard paper formats (A4, Letter, Legal).",
    category: "Pages",
    href: "/change-page-size",
    icon: "Ratio",
    status: "implemented",
    seoTitle: "Change PDF Page Format",
    seoDescription: "Change document pages to standard paper formats.",
    keywords: ["change page size pdf", "convert pdf size"],
  },
  {
    id: "a4-pdf",
    name: "A4 PDF",
    description: "Standardize all PDF pages to standard A4 format (210 x 297 mm).",
    category: "Pages",
    href: "/a4-pdf",
    icon: "FileText",
    status: "implemented",
    seoTitle: "Convert PDF to A4 Size",
    seoDescription: "Resize and adjust PDF page content to standard A4 paper size.",
    keywords: ["a4 pdf", "convert pdf to a4"],
  },
  {
    id: "a3-pdf",
    name: "A3 PDF",
    description: "Standardize PDF pages to A3 paper format (297 x 420 mm).",
    category: "Pages",
    href: "/a3-pdf",
    icon: "FileText",
    status: "implemented",
    seoTitle: "Convert PDF to A3 Size",
    seoDescription: "Resize PDF pages to large format A3 size.",
    keywords: ["a3 pdf", "convert pdf to a3"],
  },
  {
    id: "letter-pdf",
    name: "Letter PDF",
    description: "Standardize PDF pages to US Letter format (8.5 x 11 in).",
    category: "Pages",
    href: "/letter-pdf",
    icon: "FileText",
    status: "implemented",
    seoTitle: "Convert PDF to US Letter Size",
    seoDescription: "Convert document pages to US Letter standard paper dimensions.",
    keywords: ["letter size pdf", "us letter pdf"],
  },
  {
    id: "legal-pdf",
    name: "Legal PDF",
    description: "Standardize PDF pages to US Legal format (8.5 x 14 in).",
    category: "Pages",
    href: "/legal-pdf",
    icon: "FileText",
    status: "implemented",
    seoTitle: "Convert PDF to US Legal Size",
    seoDescription: "Format document pages to US Legal paper dimensions.",
    keywords: ["legal size pdf", "us legal pdf"],
  },
  {
    id: "custom-page-size",
    name: "Custom Page Size",
    description: "Set exact custom width and height dimensions for PDF pages.",
    category: "Pages",
    href: "/custom-page-size",
    icon: "Ruler",
    status: "implemented",
    seoTitle: "Custom PDF Page Dimensions",
    seoDescription: "Define exact custom dimensions in mm, inches, or points for PDF pages.",
    keywords: ["custom pdf page size", "set pdf width height"],
  },
  {
    id: "add-margins",
    name: "Add Margins",
    description: "Add white outer padding/margins around document pages.",
    category: "Pages",
    href: "/add-margins",
    icon: "Square",
    status: "implemented",
    seoTitle: "Add Margins to PDF Pages",
    seoDescription: "Add uniform or custom margins around page content for printing.",
    keywords: ["add margins to pdf", "pdf page padding"],
  },
  {
    id: "remove-margins",
    name: "Remove Margins",
    description: "Trim unnecessary whitespace margins around PDF pages.",
    category: "Pages",
    href: "/remove-margins",
    icon: "Minimize2",
    status: "implemented",
    seoTitle: "Remove PDF Margins",
    seoDescription: "Trim outer whitespace margins to maximize printable page area.",
    keywords: ["remove pdf margins", "crop white space pdf"],
  },
  {
    id: "center-page-content",
    name: "Center Page Content",
    description: "Automatically center page content inside printable boundaries.",
    category: "Pages",
    href: "/center-page-content",
    icon: "AlignCenter",
    status: "implemented",
    seoTitle: "Center Content on PDF Pages",
    seoDescription: "Center page content horizontally and vertically on PDF pages.",
    keywords: ["center pdf content", "align pdf page"],
  },
  {
    id: "fit-content-to-page",
    name: "Fit Content to Page",
    description: "Scale page content to fit within target page margins cleanly.",
    category: "Pages",
    href: "/fit-content-to-page",
    icon: "Shrink",
    status: "implemented",
    seoTitle: "Fit Content to PDF Page Size",
    seoDescription: "Automatically scale page elements to fit inside standard margins.",
    keywords: ["fit to page pdf", "scale content pdf"],
  },
  {
    id: "scale-pdf",
    name: "Scale PDF",
    description: "Scale PDF page content up or down by percentage.",
    category: "Pages",
    href: "/scale-pdf",
    icon: "Expand",
    status: "implemented",
    seoTitle: "Scale PDF Pages Up or Down",
    seoDescription: "Proportionally scale page content up or down by custom percentage.",
    keywords: ["scale pdf", "zoom pdf content"],
  },
  {
    id: "reverse-pages",
    name: "Reverse Pages",
    description: "Reverse the order of pages in a document (last page first).",
    category: "Pages",
    href: "/reverse-pages",
    icon: "ArrowDownUp",
    status: "implemented",
    seoTitle: "Reverse PDF Page Order",
    seoDescription: "Reverse page sequence so the last page comes first.",
    keywords: ["reverse page order pdf", "invert pdf pages"],
  },
  {
    id: "remove-blank-pages",
    name: "Remove Blank Pages",
    description: "Detect and remove empty or blank pages from a PDF.",
    category: "Pages",
    href: "/remove-blank-pages",
    icon: "Eraser",
    status: "implemented",
    seoTitle: "Remove Blank Pages from PDF",
    seoDescription: "Automatically identify and delete blank or empty pages from PDFs.",
    keywords: ["remove blank pages pdf", "delete empty pages"],
  },
  {
    id: "extract-odd-pages",
    name: "Extract Odd Pages",
    description: "Create a new document containing only odd-numbered pages (1, 3, 5...).",
    category: "Pages",
    href: "/extract-odd-pages",
    icon: "Hash",
    status: "implemented",
    seoTitle: "Extract Odd Pages from PDF",
    seoDescription: "Extract odd-numbered pages into an independent PDF document.",
    keywords: ["extract odd pages pdf", "odd pages pdf"],
  },
  {
    id: "extract-even-pages",
    name: "Extract Even Pages",
    description: "Create a new document containing only even-numbered pages (2, 4, 6...).",
    category: "Pages",
    href: "/extract-even-pages",
    icon: "Hash",
    status: "implemented",
    seoTitle: "Extract Even Pages from PDF",
    seoDescription: "Extract even-numbered pages into an independent PDF document.",
    keywords: ["extract even pages pdf", "even pages pdf"],
  },

  // ==========================================
  // Category 3: Convert (16 Tools)
  // ==========================================
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG images into a single clean PDF document.",
    category: "Convert",
    href: "/jpg-to-pdf",
    icon: "FileImage",
    status: "implemented",
    seoTitle: "Convert JPG to PDF Free Online",
    seoDescription: "Convert JPG and JPEG images into a single PDF document in your browser.",
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf"],
    seoH1: "JPG to PDF Online Free",
    seoH2s: ["How to JPG to PDF", "Related Tools"],
    introParagraph: "Easily jpg to pdf directly in your browser. Our free tool provides a fast, secure, and private way to process your files without any uploads.",
    howTo: {
      name: "How to JPG to PDF",
      description: "Learn how to jpg to pdf in a few simple steps.",
      steps: [
        { name: "Upload File", text: "Select your file or drag and drop it into the tool." },
        { name: "Adjust Settings", text: "Choose your preferred options for processing." },
        { name: "Download", text: "Click to process and instantly download your new file." }
      ]
    },
    faqs: [
      { question: "Is this JPG to PDF tool free?", answer: "Yes, it is completely free to use with no hidden limits." },
      { question: "Are my files secure?", answer: "Yes, all processing happens locally in your browser. Your files are never uploaded to any server." }
    ],
    relatedTools: ["merge-pdf", "split-pdf", "compress-pdf"],
  },
  {
    id: "png-to-pdf",
    name: "PNG to PDF",
    description: "Convert PNG images into a PDF document with transparency support.",
    category: "Convert",
    href: "/png-to-pdf",
    icon: "Image",
    status: "implemented",
    seoTitle: "Convert PNG to PDF Online Free",
    seoDescription: "Convert PNG graphics into PDF documents with custom page margins.",
    keywords: ["png to pdf", "image to pdf"],
  },
  {
    id: "webp-to-pdf",
    name: "WebP to PDF",
    description: "Convert WebP images into a high quality PDF document.",
    category: "Convert",
    href: "/webp-to-pdf",
    icon: "Image",
    status: "implemented",
    seoTitle: "Convert WebP to PDF Free",
    seoDescription: "Convert WebP images directly into PDF documents in your browser.",
    keywords: ["webp to pdf", "convert webp to pdf"],
  },
  {
    id: "gif-to-pdf",
    name: "GIF to PDF",
    description: "Convert static or animated GIF frames into a PDF.",
    category: "Convert",
    href: "/gif-to-pdf",
    icon: "Image",
    status: "implemented",
    seoTitle: "Convert GIF to PDF Free",
    seoDescription: "Convert GIF image frames into PDF document pages.",
    keywords: ["gif to pdf", "convert gif to pdf"],
  },
  {
    id: "bmp-to-pdf",
    name: "BMP to PDF",
    description: "Convert bitmap images into standard PDF files.",
    category: "Convert",
    href: "/bmp-to-pdf",
    icon: "Image",
    status: "implemented",
    seoTitle: "Convert BMP to PDF Free",
    seoDescription: "Convert BMP bitmap images into clean PDF documents.",
    keywords: ["bmp to pdf", "bitmap to pdf"],
  },
  {
    id: "tiff-to-pdf",
    name: "TIFF to PDF",
    description: "Convert single or multi-page TIFF images into PDF documents.",
    category: "Convert",
    href: "/tiff-to-pdf",
    icon: "Image",
    status: "implemented",
    seoTitle: "Convert TIFF to PDF Free",
    seoDescription: "Convert single or multi-frame TIFF images into PDF files.",
    keywords: ["tiff to pdf", "tif to pdf"],
  },
  {
    id: "svg-to-pdf",
    name: "SVG to PDF",
    description: "Convert SVG graphics into high-resolution PDF pages.",
    category: "Convert",
    href: "/svg-to-pdf",
    icon: "PenTool",
    status: "implemented",
    seoTitle: "Convert SVG to PDF Online Free",
    seoDescription: "Convert SVG vector files to crisp, high-resolution PDF documents. 100% free, private browser-local processing with customizable DPI up to 600.",
    keywords: ["svg to pdf", "convert svg to pdf", "svg zu pdf", "svg a pdf", "svg para pdf", "converter svg em pdf", "svg2pdf", "vector to pdf"],
    seoH1: "Convert SVG to PDF Online Free",
    seoH2s: ["How to Convert SVG to PDF", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Convert your Scalable Vector Graphics (SVG) into crisp, professional PDF documents instantly directly in your web browser. KissThePDF renders each SVG file at customizable, high-resolution fidelity (150, 300, or up to 600 DPI) and places it perfectly onto a standalone PDF page. Unlike cloud-based conversion platforms that upload your artwork to remote data centers, our conversion pipeline executes 100% locally on your machine using client-side JavaScript, WebAssembly, and HTML5 Canvas rendering. This ensures your proprietary brand logos, architectural schematics, graphic illustrations, and confidential diagrams remain completely private and never leave your computer. Whether you are preparing print-ready vector assets, converting multiple SVG icons into a multi-page PDF catalog, or archiving digital design files, KissThePDF delivers pixel-perfect clarity without color degradation. Enjoy unlimited file conversions with zero file size restrictions, no watermarks, and no sign-up or email requirements. The resulting PDF documents are universally compatible with Adobe Acrobat, Apple Preview, web browsers, and all commercial print workflows.",
    howTo: {
      name: "How to Convert SVG to PDF in 3 Steps",
      description: "Quickly convert any SVG graphic to a high-resolution PDF document right in your browser.",
      steps: [
        { name: "Select SVG Files", text: "Click Select SVG files or drag and drop your .svg artwork directly into the upload area." },
        { name: "Select Resolution (DPI)", text: "Choose your desired target resolution (150 DPI for web/email, 300 DPI for standard printing, or 600 DPI for ultra-sharp prints)." },
        { name: "Convert and Download", text: "Click Convert to PDF to generate your new document and download it immediately to your device." },
      ]
    },
    faqs: [
      { question: "Does this tool preserve vector scalability in the exported PDF?", answer: "Each SVG is rendered to a high-resolution raster image at your chosen DPI (up to 600 DPI) and placed on a PDF page. This produces sharp, high-fidelity prints while ensuring complex SVG styling, CSS, and clip-paths render consistently without font or path corruption." },
      { question: "Are external web fonts or remote images included in the SVG?", answer: "For security and privacy, browser sandbox rules prevent loading external third-party web URLs. Ensure any fonts are converted to outlines/paths or embedded as data URIs within the SVG file before converting." },
      { question: "Kann ich SVG zu PDF online kostenlos konvertieren? / \u00bfPuedo convertir SVG a PDF gratis?", answer: "Ja / S\u00ed. KissThePDF is completely free in all languages. SVG zu PDF (German), SVG a PDF (Spanish), and SVG para PDF (Portuguese) are fully supported without file limits, watermarks, or account registration." },
      { question: "Can I convert multiple SVG files into a single multi-page PDF?", answer: "Yes. You can upload multiple SVG files simultaneously, reorder them, and export them as a multi-page PDF document or download them as individual PDF files." },
      { question: "Are my SVG graphics uploaded to any cloud server?", answer: "No. KissThePDF processes everything locally inside your browser using client-side JavaScript. Your confidential illustrations and designs never leave your device." },
    ],
    relatedTools: ["png-to-pdf", "jpg-to-pdf", "images-to-pdf", "pdf-to-png", "scale-pdf"],
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine multiple images of any format into one PDF.",
    category: "Convert",
    href: "/images-to-pdf",
    icon: "Images",
    status: "implemented",
    seoTitle: "Combine Images to PDF",
    seoDescription: "Merge multiple images of different formats (JPG, PNG, WebP) into a single PDF.",
    keywords: ["images to pdf", "combine pictures to pdf"],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages into high quality JPG images.",
    category: "Convert",
    href: "/pdf-to-jpg",
    icon: "ImageDown",
    status: "implemented",
    seoTitle: "Convert PDF to JPG Online",
    seoDescription: "Convert PDF pages into high quality JPG images in your browser.",
    keywords: ["pdf to jpg", "pdf to jpeg", "convert pdf to image"],
    seoH1: "PDF to JPG Online Free",
    seoH2s: ["How to PDF to JPG", "Related Tools"],
    introParagraph: "Easily pdf to jpg directly in your browser. Our free tool provides a fast, secure, and private way to process your files without any uploads.",
    howTo: {
      name: "How to PDF to JPG",
      description: "Learn how to pdf to jpg in a few simple steps.",
      steps: [
        { name: "Upload File", text: "Select your file or drag and drop it into the tool." },
        { name: "Adjust Settings", text: "Choose your preferred options for processing." },
        { name: "Download", text: "Click to process and instantly download your new file." }
      ]
    },
    faqs: [
      { question: "Is this PDF to JPG tool free?", answer: "Yes, it is completely free to use with no hidden limits." },
      { question: "Are my files secure?", answer: "Yes, all processing happens locally in your browser. Your files are never uploaded to any server." }
    ],
    relatedTools: ["merge-pdf", "split-pdf", "compress-pdf"],
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert PDF pages to lossless PNG images.",
    category: "Convert",
    href: "/pdf-to-png",
    icon: "ImageDown",
    status: "implemented",
    seoTitle: "Convert PDF to PNG Online",
    seoDescription: "Convert PDF pages to lossless PNG images with customizable resolution.",
    keywords: ["pdf to png", "convert pdf to png"],
  },
  {
    id: "pdf-to-webp",
    name: "PDF to WebP",
    description: "Convert PDF pages to WebP images with adjustable quality.",
    category: "Convert",
    href: "/pdf-to-webp",
    icon: "ImageDown",
    status: "implemented",
    seoTitle: "Convert PDF to WebP Online",
    seoDescription: "Convert PDF pages to modern WebP images directly in your browser.",
    keywords: ["pdf to webp", "convert pdf to webp"],
  },
  {
    id: "pdf-to-tiff",
    name: "PDF to TIFF",
    description: "Convert PDF document pages to uncompressed or compressed TIFF images.",
    category: "Convert",
    href: "/pdf-to-tiff",
    icon: "ImageDown",
    status: "implemented",
    seoTitle: "Convert PDF to TIFF Free",
    seoDescription: "Convert PDF document pages to TIFF image format.",
    keywords: ["pdf to tiff", "convert pdf to tif"],
  },
  {
    id: "pdf-to-images-zip",
    name: "PDF to Images ZIP",
    description: "Export all PDF pages as images inside a single ZIP archive.",
    category: "Convert",
    href: "/pdf-to-images-zip",
    icon: "FileArchive",
    status: "implemented",
    seoTitle: "Export PDF Pages to ZIP Images",
    seoDescription: "Export every page of a PDF as individual image files bundled in a ZIP archive.",
    keywords: ["pdf to zip images", "export pdf pages zip"],
  },
  {
    id: "extract-images-from-pdf",
    name: "Extract Images from PDF",
    description: "Extract embedded bitmap images from inside a PDF document.",
    category: "Convert",
    href: "/extract-images-from-pdf",
    icon: "ScanLine",
    status: "implemented",
    seoTitle: "Extract Embedded Images from PDF",
    seoDescription: "Extract original embedded images contained inside your PDF document.",
    keywords: ["extract images from pdf", "rip images pdf"],
  },
  {
    id: "photo-album-pdf",
    name: "Photo Album PDF",
    description: "Format multiple photos into a photo album PDF layout.",
    category: "Convert",
    href: "/photo-album-pdf",
    icon: "BookImage",
    status: "implemented",
    seoTitle: "Create Photo Album PDF Online Free",
    seoDescription: "Convert multiple photos into a beautifully organized PDF photo album. Customize grid layouts, margins, and page orientations with 100% local privacy.",
    keywords: ["photo album pdf", "pdf album", "pdf photo album", "photos to pdf album", "create photo album pdf", "image album to pdf"],
    seoH1: "Create Photo Album PDF Online Free",
    seoH2s: ["How to Make a Photo Album PDF", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Transform collections of digital photographs and graphics into beautifully structured PDF photo albums in seconds. KissThePDF allows you to import batches of JPG, PNG, WebP, GIF, and BMP images and arrange them into clean, multi-image page layouts (such as 1, 2, 4, or 6 photos per page). Easily customize page orientations, adjust margin spacing, fine-tune gaps between images, and reorder photos visually using drag-and-drop cards before compiling the final album. Our client-side rendering engine embeds images at maximum resolution, ensuring high-fidelity color reproduction for family photo memories, real estate portfolios, design lookbooks, and event albums. Because the entire album generation process executes 100% locally inside your web browser, your personal memories and private photos are never uploaded to third-party cloud servers. Create unlimited PDF photo albums for free, without file size limits, watermarks, or account registration. Download compact, high-quality PDF albums ready for instant email sharing, digital archiving, or high-resolution photo book printing.",
    howTo: {
      name: "How to Create a Photo Album PDF",
      description: "Convert batches of photos into a structured PDF album in 3 easy steps.",
      steps: [
        { name: "Select Your Photos", text: "Click Select Images or drag and drop your photos into the album builder." },
        { name: "Choose Layout and Margins", text: "Select your grid layout (photos per page), orientation, margins, and spacing." },
        { name: "Build and Download PDF", text: "Click Generate Album to create your PDF photo album and download it immediately." },
      ]
    },
    faqs: [
      { question: "What image formats can I include in the photo album?", answer: "You can combine JPG, JPEG, PNG, WebP, GIF, and BMP image files in the same photo album." },
      { question: "Is there a limit on how many photos I can add?", answer: "No. You can add dozens of photos in a single batch without artificial limits or paywalls." },
      { question: "Can I reorder photos before generating the PDF album?", answer: "Yes. You can drag and drop photo cards to rearrange the visual sequence before compiling the document." },
      { question: "Does creating a photo album reduce photo resolution?", answer: "No. Photos are embedded into the PDF with high fidelity to ensure crisp prints and sharp screen viewing." },
      { question: "Are my personal photos uploaded to any web server?", answer: "No. KissThePDF processes all images locally inside your browser. Your private photos never leave your device." },
    ],
    relatedTools: ["images-to-pdf", "contact-sheet-pdf", "jpg-to-pdf", "png-to-pdf", "compress-pdf"],
  },
  {
    id: "contact-sheet-pdf",
    name: "Contact Sheet PDF",
    description: "Create a thumbnail grid contact sheet PDF from multiple images.",
    category: "Convert",
    href: "/contact-sheet-pdf",
    icon: "Grid3x3",
    status: "implemented",
    seoTitle: "Create Image Contact Sheet PDF",
    seoDescription: "Organize image thumbnails into a structured contact sheet PDF.",
    keywords: ["contact sheet pdf", "image grid pdf"],
  },

  // ==========================================
  // Category 4: Edit (18 Tools)
  // ==========================================
  {
    id: "edit-pdf",
    name: "Edit PDF",
    description: "Interactive PDF editor to add text, drawings, shapes, and annotations.",
    category: "Edit",
    href: "/edit-pdf",
    icon: "Pencil",
    status: "implemented",
    seoTitle: "Free Online PDF Editor (No Sign Up)",
    seoDescription: "Edit PDF documents directly in your browser. Add text, shapes, signatures, drawings, and annotations for free. 100% private with no account or uploads.",
    keywords: ["edit pdf", "online pdf editor", "free pdf editor", "edit pdf online", "modify pdf", "pdf editor no sign up", "edit pdf browser"],
    seoH1: "Free Online PDF Editor",
    seoH2s: ["How to Edit PDF Files Online", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Edit PDF documents online with a comprehensive suite of powerful markup and document enhancement tools designed for speed, privacy, and precision. KissThePDF allows you to add custom text boxes, insert image overlays, draw geometric shapes (rectangles, circles, arrows, lines), write freehand ink notes, highlight text, strikethrough clauses, and attach sticky comments directly to your PDF pages. Powered by client-side WebAssembly, our editor delivers instantaneous rendering without latency, file size restrictions, daily task quotas, or intrusive watermarks. Unlike cloud-based PDF editors that store your sensitive files on third-party servers, KissThePDF executes all document modifications 100% locally inside your web browser sandbox. Your confidential business contracts, tax forms, personal identification documents, and creative designs remain completely secure on your machine. Compatible across desktop and mobile browsers, KissThePDF gives you the freedom to edit, annotate, and export professional PDFs in seconds without signing up. Experience complete PDF editing freedom with full undo/redo history, layer management, and crystal-clear vector output.",
    howTo: {
      name: "How to Edit a PDF Document Online",
      description: "Add text, annotations, shapes, and drawings to any PDF in 4 easy steps.",
      steps: [
        { name: "Upload Your PDF", text: "Drag and drop your PDF document into the online editor canvas." },
        { name: "Select an Editing Tool", text: "Choose from Text, Shapes, Pen, Highlighter, Strikethrough, Image, or Sticky Notes from the toolbar." },
        { name: "Add Edits to Pages", text: "Click or drag on any page to insert text, markups, or graphical elements, and customize fonts and colors." },
        { name: "Save and Download", text: "Click Download PDF to export your newly edited document instantly to your device." },
      ]
    },
    faqs: [
      { question: "Is KissThePDF really 100% free with no limits?", answer: "Yes. KissThePDF is an open-source (MIT licensed) project. There are no paid tiers, daily usage quotas, file size limits, or watermark insertions." },
      { question: "Can I add new text and customize the font?", answer: "Yes. You can place text boxes anywhere on the document, choose font families, adjust font size, change text colors, and align text." },
      { question: "Can I add my signature to PDF documents?", answer: "Yes. You can draw a signature freehand, upload a signature image, or type your name using our built-in signature tools." },
      { question: "Are my uploaded PDFs sent to any third-party server?", answer: "No. KissThePDF runs entirely in your browser using client-side JavaScript and WebAssembly. Your documents are never uploaded, logged, or shared." },
      { question: "Which operating systems and browsers are supported?", answer: "KissThePDF works smoothly on Google Chrome, Apple Safari, Mozilla Firefox, Microsoft Edge, and modern mobile browsers across Windows, macOS, Linux, iOS, and Android." },
    ],
    relatedTools: ["strikethrough-pdf", "add-text", "draw-on-pdf", "add-circle", "sticky-notes", "sign-pdf"],
  },
  {
    id: "add-text",
    name: "Add Text",
    description: "Place text overlays, titles, and paragraphs anywhere on PDF pages.",
    category: "Edit",
    href: "/add-text",
    icon: "Type",
    status: "implemented",
    seoTitle: "Add Text to PDF Online",
    seoDescription: "Place new text blocks onto PDF pages with custom font sizes and colors.",
    keywords: ["add text to pdf", "write on pdf"],
  },
  {
    id: "add-image",
    name: "Add Image",
    description: "Insert and position images or logos onto PDF document pages.",
    category: "Edit",
    href: "/add-image",
    icon: "ImagePlus",
    status: "implemented",
    seoTitle: "Insert Image into PDF",
    seoDescription: "Insert image logos or photos onto specific page coordinates.",
    keywords: ["insert image in pdf", "add picture to pdf"],
  },
  {
    id: "add-shape",
    name: "Add Shape",
    description: "Insert rectangles, circles, arrows, and custom shapes into PDFs.",
    category: "Edit",
    href: "/add-shape",
    icon: "Shapes",
    status: "implemented",
    seoTitle: "Add Shapes to PDF",
    seoDescription: "Add geometric shapes and callout boxes onto PDF pages.",
    keywords: ["add shape to pdf", "draw shapes pdf"],
  },
  {
    id: "draw-on-pdf",
    name: "Draw on PDF",
    description: "Freehand drawing tool with pen width and color controls.",
    category: "Edit",
    href: "/draw-on-pdf",
    icon: "PenLine",
    status: "implemented",
    seoTitle: "Draw on PDF Online Free (No Upload)",
    seoDescription: "Draw, sketch, and scribble on PDF pages directly in your browser. Free online markup tool with customizable stroke colors, sizes, and undo support.",
    keywords: ["draw on pdf", "draw on pdf online", "pdf drawing tool", "sketch on pdf", "freehand drawing pdf", "annotate pdf free"],
    seoH1: "Draw on PDF Online Free",
    seoH2s: ["How to Draw on a PDF Document", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Scribble annotations, draw freehand diagrams, highlight key passages, and markup PDF pages with our free in-browser drawing toolkit. KissThePDF provides a versatile drawing canvas that lets you write, sketch, and doodle across single or multi-page PDF documents without installing third-party software or paying monthly subscription fees. Switch effortlessly between freehand pens, highlighters, geometric shapes, and precision erasers while tailoring colors and brush widths to your exact project needs. Drawn elements are embedded cleanly as permanent vector paths within the PDF structure, ensuring universal compatibility across Adobe Acrobat, Apple Preview, Google Drive, and mobile PDF viewers. Because KissThePDF executes all rendering and document compilation locally in your browser using WebAssembly, your confidential files, drawings, and personal markups are never transmitted over the internet. Enjoy rapid, private PDF markup with no file size limitations, no account creation, and zero watermarks. Whether marking up blueprints, grading student essays, or adding quick notes to receipts, KissThePDF provides the ultimate client-side drawing experience.",
    howTo: {
      name: "How to Draw on a PDF Online",
      description: "Annotate and draw directly onto PDF pages in 4 quick steps.",
      steps: [
        { name: "Open Your PDF", text: "Drag and drop your PDF into the interactive drawing canvas." },
        { name: "Select Drawing Mode", text: "Choose the Draw or Pen tool and pick your stroke color and brush thickness." },
        { name: "Annotate the Page", text: "Draw freely across any page of your document using your mouse, trackpad, or touchscreen." },
        { name: "Download PDF", text: "Click Download PDF to export your newly annotated document immediately." },
      ]
    },
    faqs: [
      { question: "Can I draw on multiple pages of a single PDF?", answer: "Yes. You can scroll through the entire document and draw annotations across any page in the file." },
      { question: "Can I change the stroke thickness and color while drawing?", answer: "Yes. The toolbar allows you to switch between different colors, opacity levels, and stroke widths at any point during your editing session." },
      { question: "Will my drawings be visible in all PDF readers?", answer: "Yes. Drawn strokes are saved into the PDF content stream, ensuring full compatibility with Adobe Acrobat, Apple Preview, Google Drive, and mobile apps." },
      { question: "Is there a limit on how many drawings or pages I can annotate?", answer: "No. KissThePDF is completely free and has no arbitrary page or file size limitations." },
      { question: "Does KissThePDF upload my PDF to any server?", answer: "No. All PDF processing and drawing happens 100% locally in your web browser." },
    ],
    relatedTools: ["pen-tool", "eraser", "add-shape", "edit-pdf", "add-circle", "sign-pdf"],
  },
  {
    id: "pen-tool",
    name: "Pen Tool",
    description: "Precision pen tool for smooth freehand drawing and sketching.",
    category: "Edit",
    href: "/pen-tool",
    icon: "Pen",
    status: "implemented",
    seoTitle: "PDF Pen Tool: Freehand Draw Online",
    seoDescription: "Draw freehand, sketch annotations, and write on PDF documents online with a responsive pen tool. 100% free, private, and runs in your browser.",
    keywords: ["pdf pen tool", "pen pdf", "draw on pdf", "freehand draw pdf", "pdf pen annotation", "write on pdf free"],
    seoH1: "PDF Pen Tool: Draw and Write on PDF Online",
    seoH2s: ["How to Use the PDF Pen Tool", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Draw freehand, sketch diagrams, write handwritten notes, and circle important details with an ultra-responsive digital pen tool built directly into your web browser. KissThePDF delivers smooth, fluid digital inking with full hardware acceleration and support for mouse, trackpad, touchscreen, and digital stylus inputs including Apple Pencil and Microsoft Surface Pen. Customize ink colors with a comprehensive palette, adjust stroke thickness and opacity, and take advantage of automatic line smoothing for legible handwritten notes and clear sketch markups. Every stroke is encoded as a crisp vector path directly into the PDF content stream, ensuring that your drawings maintain razor-sharp resolution at any zoom level or high-DPI print setting. All document processing and vector calculations happen 100% locally on your computer with zero server uploads, keeping your private thoughts, lecture notes, and sensitive sketches safe on your machine. Switch effortlessly between different pen modes, highlight key passages, undo accidental strokes, and download your annotated PDF file instantly without account creation or subscription fees.",
    howTo: {
      name: "How to Draw on a PDF with the Pen Tool",
      description: "Follow these simple steps to write or sketch on any PDF page.",
      steps: [
        { name: "Upload Document", text: "Open your PDF file inside the PDF Pen Tool editor." },
        { name: "Configure Pen Settings", text: "Select the Pen tool and pick your stroke color, line thickness, and opacity." },
        { name: "Draw or Write Freehand", text: "Use your mouse, finger, or stylus to draw, sketch diagrams, or write handwritten annotations." },
        { name: "Save Your PDF", text: "Click Download PDF to export your document with crisp vector drawing paths included." },
      ]
    },
    faqs: [
      { question: "Can I use a stylus or Apple Pencil with the PDF Pen Tool?", answer: "Yes. KissThePDF supports touch and pointer events, providing responsive inking on iPad, tablet devices, touch-enabled laptops, and graphic drawing tablets." },
      { question: "How do I erase or undo a pen stroke?", answer: "You can click the Undo button in the top toolbar to remove the latest stroke, or use the Eraser tool to click and remove individual drawn strokes." },
      { question: "Can I use the pen tool to sign PDF documents?", answer: "Yes. You can write your signature directly on contracts or authorization forms with the pen tool, or use our dedicated Sign PDF tool for signature management." },
      { question: "Does drawing with the pen tool reduce PDF sharpness or print quality?", answer: "No. Drawn strokes are embedded as crisp vector paths within the PDF, maintaining maximum resolution at any zoom level or print scale." },
      { question: "Are my drawn notes or files transmitted to any server?", answer: "No. All drawing computations and PDF compilation run entirely in your local browser sandbox." },
    ],
    relatedTools: ["draw-on-pdf", "eraser", "edit-pdf", "add-circle", "highlight-pdf", "sign-pdf"],
  },
  {
    id: "eraser",
    name: "Eraser",
    description: "Erase drawings, shapes, or added text overlays from PDF pages.",
    category: "Edit",
    href: "/eraser",
    icon: "Eraser",
    status: "implemented",
    seoTitle: "PDF Eraser Tool",
    seoDescription: "Erase added annotations, drawings, and shapes from PDF pages.",
    keywords: ["pdf eraser", "erase notes pdf"],
  },
  {
    id: "highlight-pdf",
    name: "Highlight PDF",
    description: "Highlight text and key sections with translucent highlighter colors.",
    category: "Edit",
    href: "/highlight-pdf",
    icon: "Highlighter",
    status: "implemented",
    seoTitle: "Highlight PDF Text Online",
    seoDescription: "Highlight text lines and paragraphs with translucent color overlays.",
    keywords: ["highlight pdf", "pdf text highlighter"],
  },
  {
    id: "underline-pdf",
    name: "Underline PDF",
    description: "Add underline annotations to document text.",
    category: "Edit",
    href: "/underline-pdf",
    icon: "Underline",
    status: "implemented",
    seoTitle: "Underline PDF Text",
    seoDescription: "Add underline markup annotations to PDF document text.",
    keywords: ["underline text pdf", "markup pdf"],
  },
  {
    id: "strikethrough-pdf",
    name: "Strikethrough PDF",
    description: "Add strikethrough lines over PDF document text.",
    category: "Edit",
    href: "/strikethrough-pdf",
    icon: "Strikethrough",
    status: "implemented",
    seoTitle: "Strikethrough PDF Text Online Free",
    seoDescription: "Cross out and strikethrough text in PDF documents online. Free browser-based annotation tool with custom line colors, thickness, and undo support.",
    keywords: ["strikethrough pdf", "strikethrough on pdf", "strikethrough in pdf", "how to strikethrough text in pdf", "pdf strikethrough", "cross out text pdf"],
    seoH1: "Strikethrough Text in PDF Online Free",
    seoH2s: ["How to Strikethrough Text in a PDF", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Add clean, professional strikethrough annotations across text, clauses, contract terms, or paragraphs in your PDF documents without installing complex desktop software. KissThePDF provides a responsive, browser-native PDF editor that lets you cross out text with precision accuracy. Easily customize strikethrough line colors (such as editorial red, subtle gray, or bold black), adjust stroke thickness to match document typography, and undo or reposition annotations on the fly. Because the entire rendering engine and PDF modification process runs 100% locally inside your web browser via WebAssembly, your confidential legal agreements, financial statements, academic papers, and private records remain strictly secure on your device. Our non-destructive annotation layer keeps the underlying text intact while adding standard PDF vector strikeout markup that displays flawlessly across Adobe Acrobat, Apple Preview, Google Chrome, and mobile PDF readers. No account creation, no file uploads, and no daily usage limits\u2014simply open your document, strike through unwanted content, and export your polished PDF in seconds. It provides the fastest, safest way for lawyers, students, editors, and business professionals to perform collaborative document markup.",
    howTo: {
      name: "How to Strikethrough Text in a PDF in 4 Steps",
      description: "Cross out unwanted text or mark edits in your PDF document with a clean strikethrough annotation.",
      steps: [
        { name: "Open Your PDF", text: "Upload or drag and drop your PDF document into the Strikethrough PDF editor." },
        { name: "Select the Strikethrough Tool", text: "Click the Strikeout tool icon from the toolbar and choose your preferred line color and stroke width." },
        { name: "Draw Over the Text", text: "Click and drag your mouse or stylus across the words or sentences you want to cross out." },
        { name: "Save and Download", text: "Click Save Changes or Download PDF to export your annotated document with permanent markup." },
      ]
    },
    faqs: [
      { question: "Does strikethrough delete or erase the text underneath?", answer: "No. A strikethrough draws an annotation line across the selected text while keeping the underlying text intact. If you need to permanently redact or hide sensitive information, use our Whiteout or Redact tool instead." },
      { question: "Can I customize the color and thickness of the strikethrough line?", answer: "Yes. You can select any color from the palette (red, black, blue, gray, etc.) and adjust the stroke width to match your document typography." },
      { question: "How do I remove or undo a strikethrough line?", answer: "Click the Undo button in the top toolbar, or switch to the Select tool, click on the strikethrough line annotation, and press Delete or Backspace." },
      { question: "Will my strikethrough annotations show up in Adobe Acrobat and Preview?", answer: "Yes. The annotations are saved standard PDF vector graphics that display accurately in Adobe Acrobat, Apple Preview, Google Chrome, and all PDF viewers." },
      { question: "Is my PDF uploaded to any third-party server?", answer: "No. KissThePDF processes your PDF entirely within your browser memory. Your sensitive documents never leave your computer." },
    ],
    relatedTools: ["highlight-pdf", "underline-pdf", "whiteout-pdf", "edit-pdf", "pdf-comments", "sticky-notes"],
  },
  {
    id: "add-arrow",
    name: "Add Arrow",
    description: "Draw directional arrow pointers onto PDF document pages.",
    category: "Edit",
    href: "/add-arrow",
    icon: "ArrowRight",
    status: "implemented",
    seoTitle: "Add Arrow Pointer to PDF",
    seoDescription: "Insert directional arrows to point out key document details.",
    keywords: ["add arrow to pdf", "arrow annotation pdf"],
  },
  {
    id: "add-line",
    name: "Add Line",
    description: "Draw straight lines with custom stroke thickness and color.",
    category: "Edit",
    href: "/add-line",
    icon: "Minus",
    status: "implemented",
    seoTitle: "Add Straight Line to PDF",
    seoDescription: "Draw straight lines across PDF pages.",
    keywords: ["add line to pdf", "draw line pdf"],
  },
  {
    id: "add-rectangle",
    name: "Add Rectangle",
    description: "Draw rectangular boxes and frames on PDF pages.",
    category: "Edit",
    href: "/add-rectangle",
    icon: "Square",
    status: "implemented",
    seoTitle: "Add Rectangle Box to PDF",
    seoDescription: "Insert rectangular boxes with stroke and fill options.",
    keywords: ["add rectangle pdf", "draw box pdf"],
  },
  {
    id: "add-circle",
    name: "Add Circle",
    description: "Draw circular or elliptical annotation overlays.",
    category: "Edit",
    href: "/add-circle",
    icon: "Circle",
    status: "implemented",
    seoTitle: "Add Circle to PDF Online Free",
    seoDescription: "Draw circles, ovals, and ellipses on PDF documents. Free online markup tool with customizable stroke colors, fill opacity, and border thickness.",
    keywords: ["add circle to pdf", "how to circle in pdf", "how to add circle to pdf", "draw circle on pdf", "pdf circle", "circle shape in pdf"],
    seoH1: "Add Circle to PDF Online Free",
    seoH2s: ["How to Draw a Circle on a PDF", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Highlight important numbers, call out diagram elements, circle signatures, and draw attention to critical contract clauses with our free online PDF circle tool. KissThePDF allows you to draw smooth geometric circles, ovals, and ellipses directly onto any PDF page with customizable stroke colors, adjustable border thickness, and transparent or semi-transparent background fills. Using our interactive canvas, you can easily reposition, scale, rotate, or delete circle markup after placement, or hold the Shift key to snap the bounding box into a perfect geometric circle. All PDF rendering and annotation modifications execute entirely inside your local web browser sandbox without uploading your files to remote third-party servers. This guarantees complete confidentiality for medical charts, engineering blueprints, financial audits, and personal identification documents. Whether preparing educational study guides, marking architectural drawings, or reviewing business contracts, KissThePDF provides instantaneous annotation capabilities across multi-page documents without watermarks, registration, or file size caps. Save your completed markups as standard PDF vector annotations that render with razor-sharp fidelity in any PDF viewer or printing press.",
    howTo: {
      name: "How to Add a Circle to a PDF in 4 Steps",
      description: "Insert circular or elliptical annotations on any PDF page in seconds.",
      steps: [
        { name: "Upload PDF Document", text: "Drag and drop your PDF into the interactive editor canvas." },
        { name: "Choose Circle Tool", text: "Select the Ellipse/Circle tool from the shape menu and pick your desired border color and stroke weight." },
        { name: "Draw the Circle", text: "Click and drag on the document page to create a circle or oval. Hold Shift while dragging for a perfect circle." },
        { name: "Export PDF", text: "Adjust position or dimensions as needed, then click Download to save your modified PDF." },
      ]
    },
    faqs: [
      { question: "How do I draw a perfect circle instead of an oval?", answer: "Click the circle tool and hold the Shift key while dragging on the document canvas to lock the aspect ratio into a perfect circle." },
      { question: "Can I change the circle border color and background fill?", answer: "Yes. You can customize the border color, border thickness, fill color, and fill opacity (from completely transparent to opaque) in the properties panel." },
      { question: "Can I move or resize the circle after placing it?", answer: "Yes. Switch to the Select tool (arrow icon), click on the circle, and use the bounding box handles to move, resize, or delete it." },
      { question: "Does adding circles work on multi-page PDFs?", answer: "Yes. You can navigate between pages in the document and add circles, annotations, and shapes across any page." },
      { question: "Are my files uploaded or stored on any server?", answer: "No. KissThePDF is an open-source, client-side application. All PDF rendering and drawing happens 100% inside your web browser." },
    ],
    relatedTools: ["add-rectangle", "add-arrow", "add-line", "draw-on-pdf", "pen-tool", "add-shape"],
  },
  {
    id: "add-polygon",
    name: "Add Polygon",
    description: "Draw multi-point polygon shapes on PDF pages.",
    category: "Edit",
    href: "/add-polygon",
    icon: "Triangle",
    status: "implemented",
    seoTitle: "Add Polygon Shape to PDF",
    seoDescription: "Draw multi-sided custom polygon shapes on PDF pages.",
    keywords: ["add polygon pdf", "draw polygon"],
  },
  {
    id: "sticky-notes",
    name: "Sticky Notes",
    description: "Place yellow or custom sticky note comments on PDF pages.",
    category: "Edit",
    href: "/sticky-notes",
    icon: "StickyNote",
    status: "implemented",
    seoTitle: "Add Sticky Notes to PDF Online Free",
    seoDescription: "Attach pop-up sticky notes and comment callouts to PDF pages online. Free, private, and runs locally in your browser with zero server uploads.",
    keywords: ["sticky notes pdf", "pdf sticky notes", "add sticky notes to pdf", "how to add sticky notes to pdf", "pdf post it notes", "add sticky note to pdf"],
    seoH1: "Add Sticky Notes to PDF Online Free",
    seoH2s: ["How to Add Sticky Notes to a PDF", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Attach expandable sticky notes, editorial review callouts, and structured comments to any page in your PDF documents without expensive software subscriptions. KissThePDF provides an intuitive annotation tool that lets you place clickable sticky note icons anywhere on your document canvas and attach rich textual feedback. Ideal for legal contract revisions, peer-reviewing academic research, grading student assignments, and collaborative team reviews, each note expands on hover or click into a detailed comment box. All notes are saved as standard PDF text annotations that seamlessly display in Adobe Acrobat, Apple Preview, PDF-XChange, and modern web browsers. Because our entire PDF processing engine operates 100% locally in your browser memory, your confidential business strategies, private notes, and internal documents remain completely secure on your computer. Enjoy fast, private document collaboration with zero uploads, no file size caps, and instant PDF downloads. Easily move, edit, or delete notes during your review session and export an annotated document ready for immediate sharing with colleagues and clients.",
    howTo: {
      name: "How to Add Sticky Notes to a PDF",
      description: "Place sticky note annotations and comment callouts on PDF pages in seconds.",
      steps: [
        { name: "Load Your PDF", text: "Drag and drop your document into the Sticky Notes tool." },
        { name: "Select Sticky Note Tool", text: "Click the Sticky Note icon in the annotation toolbar." },
        { name: "Position and Type Note", text: "Click on the document page where you want the comment callout to appear, then type your note text in the popup." },
        { name: "Download PDF", text: "Review all placed notes and click Download to export the annotated PDF." },
      ]
    },
    faqs: [
      { question: "How do sticky notes appear in PDF viewers like Adobe Acrobat?", answer: "Sticky notes are saved as standard PDF Text Annotations. In Adobe Acrobat, Apple Preview, and browser viewers, they appear as clickable note icons that expand into full comment popups when clicked or hovered." },
      { question: "Can I move or delete a sticky note after adding it?", answer: "Yes. Switch to the Select tool, click on the sticky note icon to open its properties, drag it to a new location, or click the delete button to remove it." },
      { question: "Can other people read and reply to my sticky notes?", answer: "Yes. Anyone who opens the exported PDF in a standard PDF reader can click the note icons to read your feedback and add replies." },
      { question: "Does adding sticky notes modify the underlying document text?", answer: "No. Sticky notes are non-destructive annotation layers that sit on top of the document without altering existing page text or layout." },
      { question: "Are my comments or documents saved on any external servers?", answer: "No. KissThePDF is 100% client-side. All processing happens in your browser memory and disappears when you close the tab." },
    ],
    relatedTools: ["pdf-comments", "edit-pdf", "highlight-pdf", "strikethrough-pdf", "pen-tool", "add-text"],
  },
  {
    id: "pdf-comments",
    name: "PDF Comments",
    description: "View and add text comments to document pages.",
    category: "Edit",
    href: "/pdf-comments",
    icon: "MessageSquare",
    status: "implemented",
    seoTitle: "Add PDF Comments & Annotations",
    seoDescription: "Add comment threads and text feedback to PDF pages.",
    keywords: ["pdf comments", "annotate pdf"],
  },
  {
    id: "whiteout-pdf",
    name: "Whiteout PDF",
    description: "Cover sensitive areas or text with a white opaque block.",
    category: "Edit",
    href: "/whiteout-pdf",
    icon: "Paintbrush",
    status: "implemented",
    seoTitle: "Whiteout PDF Content",
    seoDescription: "Cover sensitive information with an opaque whiteout overlay.",
    keywords: ["whiteout pdf", "hide text pdf", "redact pdf"],
  },

  // ==========================================
  // Category 5: Security (9 Tools)
  // ==========================================
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "Password protect your PDF with strong user and owner passwords.",
    category: "Security",
    href: "/protect-pdf",
    icon: "Lock",
    status: "implemented",
    seoTitle: "Password Protect PDF Online",
    seoDescription: "Add password encryption to restrict reading or modifying your PDF.",
    keywords: ["protect pdf", "password protect pdf", "lock pdf"],
    seoH1: "Protect PDF Online Free",
    seoH2s: ["How to Protect PDF", "Related Tools"],
    introParagraph: "Easily protect pdf directly in your browser. Our free tool provides a fast, secure, and private way to process your files without any uploads.",
    howTo: {
      name: "How to Protect PDF",
      description: "Learn how to protect pdf in a few simple steps.",
      steps: [
        { name: "Upload File", text: "Select your file or drag and drop it into the tool." },
        { name: "Adjust Settings", text: "Choose your preferred options for processing." },
        { name: "Download", text: "Click to process and instantly download your new file." }
      ]
    },
    faqs: [
      { question: "Is this Protect PDF tool free?", answer: "Yes, it is completely free to use with no hidden limits." },
      { question: "Are my files secure?", answer: "Yes, all processing happens locally in your browser. Your files are never uploaded to any server." }
    ],
    relatedTools: ["merge-pdf", "split-pdf", "compress-pdf"],
  },
  {
    id: "remove-pdf-password",
    name: "Remove PDF Password",
    description: "Remove password protection from authorized PDF files.",
    category: "Security",
    href: "/remove-pdf-password",
    icon: "LockOpen",
    status: "implemented",
    seoTitle: "Remove PDF Password Protection",
    seoDescription: "Unlock password-protected PDF files when authorized.",
    keywords: ["remove pdf password", "unlock pdf"],
  },
  {
    id: "encrypt-pdf",
    name: "Encrypt PDF",
    description: "Encrypt document contents using standard AES encryption.",
    category: "Security",
    href: "/encrypt-pdf",
    icon: "Shield",
    status: "implemented",
    seoTitle: "Encrypt PDF Files Online",
    seoDescription: "Encrypt PDF files locally with strong encryption algorithms.",
    keywords: ["encrypt pdf", "pdf encryption"],
  },
  {
    id: "decrypt-pdf",
    name: "Decrypt PDF",
    description: "Decrypt encrypted PDF documents with password authorization.",
    category: "Security",
    href: "/decrypt-pdf",
    icon: "ShieldOff",
    status: "implemented",
    seoTitle: "Decrypt PDF Files Online",
    seoDescription: "Decrypt encrypted PDF files directly in your browser.",
    keywords: ["decrypt pdf", "pdf decryption"],
  },
  {
    id: "pdf-permissions",
    name: "PDF Permissions",
    description: "Manage printing, copying, editing, and comment permissions.",
    category: "Security",
    href: "/pdf-permissions",
    icon: "KeyRound",
    status: "implemented",
    seoTitle: "Set PDF Document Permissions",
    seoDescription: "Configure allowed actions for PDF files (printing, copying, editing).",
    keywords: ["pdf permissions", "restrict printing pdf"],
  },
  {
    id: "printing-permissions",
    name: "Printing Permissions",
    description: "Allow or prevent high-resolution printing of your PDF.",
    category: "Security",
    href: "/printing-permissions",
    icon: "Printer",
    status: "implemented",
    seoTitle: "Control PDF Printing Permissions",
    seoDescription: "Restrict or enable document printing rights.",
    keywords: ["disable printing pdf", "printing permissions"],
  },
  {
    id: "copy-permissions",
    name: "Copy Permissions",
    description: "Restrict text and image copying from document pages.",
    category: "Security",
    href: "/copy-permissions",
    icon: "Copy",
    status: "implemented",
    seoTitle: "Restrict Text Copying in PDF",
    seoDescription: "Prevent unauthorized copying of text and content from your PDF.",
    keywords: ["prevent copy pdf", "copy permissions"],
  },
  {
    id: "editing-permissions",
    name: "Editing Permissions",
    description: "Lock document pages to prevent modification or page extraction.",
    category: "Security",
    href: "/editing-permissions",
    icon: "FilePenLine",
    status: "implemented",
    seoTitle: "Set PDF Editing Restrictions",
    seoDescription: "Prevent unauthorized edits or page modifications in your PDF.",
    keywords: ["prevent editing pdf", "edit permissions"],
  },
  {
    id: "comment-permissions",
    name: "Comment Permissions",
    description: "Control whether readers can add annotations or fill forms.",
    category: "Security",
    href: "/comment-permissions",
    icon: "MessageCircle",
    status: "implemented",
    seoTitle: "Control PDF Commenting Rights",
    seoDescription: "Restrict or grant commenting and annotation privileges on your PDF.",
    keywords: ["comment permissions pdf"],
  },

  // ==========================================
  // Category 6: Forms (13 Tools)
  // ==========================================
  {
    id: "remove-pdf-metadata",
    name: "Remove PDF Metadata",
    description: "Strip author, title, creation date, and hidden metadata from PDF.",
    category: "Forms",
    href: "/remove-pdf-metadata",
    icon: "FileX",
    status: "implemented",
    seoTitle: "Remove PDF Metadata & Properties",
    seoDescription: "Strip hidden document author, title, keywords, and creation metadata.",
    keywords: ["remove pdf metadata", "clean pdf properties"],
  },
  {
    id: "edit-pdf-metadata",
    name: "Edit PDF Metadata",
    description: "Edit document Title, Author, Subject, Creator, and Keywords.",
    category: "Forms",
    href: "/edit-pdf-metadata",
    icon: "FileCog",
    status: "implemented",
    seoTitle: "Edit PDF Title & Author Metadata",
    seoDescription: "Modify document metadata fields like Title, Author, Subject, and Creator.",
    keywords: ["edit pdf metadata", "pdf title author"],
  },
  {
    id: "fill-pdf-forms",
    name: "Fill PDF Forms",
    description: "Fill interactive PDF form fields directly in the browser.",
    category: "Forms",
    href: "/fill-pdf-forms",
    icon: "ClipboardList",
    status: "implemented",
    seoTitle: "Fill PDF Forms Online",
    seoDescription: "Fill text fields, checkboxes, and radio buttons in PDF forms.",
    keywords: ["fill pdf form", "pdf form filler"],
  },
  {
    id: "add-text-field",
    name: "Add Text Field",
    description: "Place interactive text input fields onto a PDF form.",
    category: "Forms",
    href: "/add-text-field",
    icon: "TextCursor",
    status: "implemented",
    seoTitle: "Add Interactive Text Field to PDF",
    seoDescription: "Insert fillable text input fields onto PDF forms.",
    keywords: ["add text field pdf", "create form field"],
  },
  {
    id: "add-checkbox",
    name: "Add Checkbox",
    description: "Insert checkable box fields into PDF documents.",
    category: "Forms",
    href: "/add-checkbox",
    icon: "CheckSquare",
    status: "implemented",
    seoTitle: "Insert Checkbox in PDF Form Online Free",
    seoDescription: "Add interactive checkable box fields to PDF forms directly in your browser. Create fillable PDF forms with custom checkbox sizes and export instantly.",
    keywords: ["insert checkbox in pdf", "add checkbox to pdf", "how to add checkbox to pdf", "add checkbox in pdf", "interactive checkbox pdf", "add checkboxes to pdf"],
    seoH1: "Insert Checkbox into PDF Forms Online",
    seoH2s: ["How to Insert a Checkbox in a PDF Form", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Transform static PDF forms into interactive, fillable documents by inserting standard clickable checkbox fields directly onto your pages. KissThePDF makes it effortless to build digital forms, inspection checklists, client onboarding questionnaires, and survey sheets in your web browser. Position checkboxes with pixel precision, customize field names, define default checked or unchecked states, and resize checkbox boundaries to match existing document layouts. The generated checkboxes follow official AcroForm specifications, ensuring complete cross-platform interactivity in Adobe Acrobat Reader, Apple Preview, Google Chrome, Microsoft Edge, and mobile PDF viewers. Because our form designer runs 100% client-side via JavaScript and WebAssembly, your confidential business forms, employee contracts, and customer agreements are never transmitted to external cloud servers. Create unlimited interactive checkboxes across multi-page forms for free, with no account registration, no watermarks, and no software installations. Easily combine checkboxes with text fields, radio buttons, and dropdowns to produce comprehensive, professional fillable PDF documents in minutes.",
    howTo: {
      name: "How to Add Checkboxes to a PDF Form",
      description: "Easily add clickable checkbox fields to any PDF form in 4 simple steps.",
      steps: [
        { name: "Upload Form Document", text: "Select or drop your PDF form into the Form Designer tool." },
        { name: "Select Checkbox Field", text: "Click the Checkbox tool from the form fields palette." },
        { name: "Place on Page", text: "Click on the document page where you want the checkbox to appear and drag to adjust its size." },
        { name: "Export Fillable PDF", text: "Set field properties or duplicate for additional items, then click Export PDF to save your interactive form." },
      ]
    },
    faqs: [
      { question: "Will the checkboxes be clickable in standard PDF readers?", answer: "Yes. KissThePDF creates standard AcroForm interactive checkbox fields that can be clicked, checked, and unchecked in Adobe Acrobat, Apple Preview, Google Chrome, Microsoft Edge, and mobile readers." },
      { question: "Can I add multiple checkboxes to create a checklist or survey?", answer: "Yes. You can add as many individual checkbox fields as needed and give each one a distinct field name and label." },
      { question: "What is the difference between a checkbox and a radio button in PDF?", answer: "Checkboxes allow users to select multiple independent options from a list, whereas radio buttons in a group restrict the user to selecting only one option at a time." },
      { question: "Can I lock or flatten the checkboxes after filling them out?", answer: "Yes. If you want to make entered checkmarks permanent and non-editable before sending the form, use our Flatten PDF Form tool." },
      { question: "Are my form documents uploaded to a cloud server?", answer: "No. KissThePDF operates 100% in your browser using client-side JavaScript. Your confidential forms never leave your device." },
    ],
    relatedTools: ["add-radio-button", "add-text-field", "add-dropdown", "flatten-pdf-form", "fill-pdf-forms", "edit-pdf"],
  },
  {
    id: "add-radio-button",
    name: "Add Radio Button",
    description: "Insert single-choice radio button groups into PDF forms.",
    category: "Forms",
    href: "/add-radio-button",
    icon: "CircleDot",
    status: "implemented",
    seoTitle: "Add Radio Buttons to PDF",
    seoDescription: "Create mutually exclusive radio button field groups.",
    keywords: ["add radio button pdf"],
  },
  {
    id: "add-dropdown",
    name: "Add Dropdown",
    description: "Add select dropdown lists with option items to PDF forms.",
    category: "Forms",
    href: "/add-dropdown",
    icon: "ChevronDown",
    status: "implemented",
    seoTitle: "Add Dropdown Select Menu to PDF",
    seoDescription: "Insert interactive dropdown select menus into PDF forms.",
    keywords: ["add dropdown pdf", "select menu pdf"],
  },
  {
    id: "add-signature-field",
    name: "Add Signature Field",
    description: "Add a designated digital signature block to a PDF.",
    category: "Forms",
    href: "/add-signature-field",
    icon: "Signature",
    status: "implemented",
    seoTitle: "Add Signature Field to PDF",
    seoDescription: "Insert interactive digital signature placeholder fields.",
    keywords: ["add signature field pdf", "signature placeholder"],
  },
  {
    id: "add-date-field",
    name: "Add Date Field",
    description: "Add auto-formatted date picker input fields to a PDF.",
    category: "Forms",
    href: "/add-date-field",
    icon: "Calendar",
    status: "implemented",
    seoTitle: "Add Date Input Field to PDF",
    seoDescription: "Insert formatted date input fields onto form pages.",
    keywords: ["add date field pdf"],
  },
  {
    id: "add-initials",
    name: "Add Initials",
    description: "Add initial boxes or stamp fields to document pages.",
    category: "Forms",
    href: "/add-initials",
    icon: "CaseSensitive",
    status: "implemented",
    seoTitle: "Add Initials to PDF Document",
    seoDescription: "Insert initial stamps and placeholders for contract sign-offs.",
    keywords: ["add initials pdf"],
  },
  {
    id: "draw-signature",
    name: "Draw Signature",
    description: "Draw your handwritten signature using a digital canvas pad.",
    category: "Forms",
    href: "/draw-signature",
    icon: "PenTool",
    status: "implemented",
    seoTitle: "Draw Signature on PDF Online",
    seoDescription: "Draw your signature on an interactive pad and place it onto document pages.",
    keywords: ["draw signature pdf", "e-sign pdf"],
  },
  {
    id: "upload-signature",
    name: "Upload Signature",
    description: "Upload an image of your signature and place it on PDF pages.",
    category: "Forms",
    href: "/upload-signature",
    icon: "Upload",
    status: "implemented",
    seoTitle: "Upload & Place Signature Image on PDF",
    seoDescription: "Upload a signature photo or PNG image and place it onto your PDF.",
    keywords: ["upload signature pdf", "sign pdf image"],
  },
  {
    id: "flatten-pdf-form",
    name: "Flatten PDF Form",
    description: "Flatten interactive form fields into non-editable page graphics.",
    category: "Forms",
    href: "/flatten-pdf-form",
    icon: "Layers",
    status: "implemented",
    seoTitle: "Flatten PDF Form Fields Online Free",
    seoDescription: "Flatten fillable PDF forms into permanent, non-editable pages. Lock form fields, checkmarks, and signatures securely in your browser without uploads.",
    keywords: ["flatten pdf form", "flatten form fields pdf", "how to flatten form fields in pdf", "lock form fields pdf", "ilovepdf flatten pdf alternative", "sejda flatten pdf alternative"],
    seoH1: "Flatten PDF Form Fields Online Free",
    seoH2s: ["How to Flatten a PDF Form", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Flatten interactive PDF form fields into permanent, non-editable page graphics to protect your completed documents against unauthorized tampering or accidental edits. When submitting filled-out tax filings, legal agreements, medical intake forms, or customer invoices, flattening bakes all entered text, checked boxes, radio button selections, and signatures directly into the visual page stream. KissThePDF automatically detects standard AcroForm fields, renders their current appearance values with typographic precision, and strips away interactive widget structures. The resulting PDF looks identical to your filled form but functions as a secure, static document that cannot be altered in PDF viewers or form fillers. Because the entire parsing and flattening operation runs 100% locally in your web browser via WebAssembly, your sensitive financial records, social security numbers, and private signatures never leave your device. Flatten unlimited PDF forms instantly without file size caps, watermarks, or account registration. Ensure complete data integrity and compliance across all standard PDF viewers and archival systems with zero cloud exposure.",
    howTo: {
      name: "How to Flatten PDF Form Fields in 3 Steps",
      description: "Lock fillable form fields and make PDF form data permanent in seconds.",
      steps: [
        { name: "Upload Fillable PDF Form", text: "Select or drag and drop your filled-out PDF form into the tool." },
        { name: "Review Detected Fields", text: "The tool automatically detects AcroForm text boxes, checkboxes, radio buttons, and signatures." },
        { name: "Flatten and Download", text: "Click Flatten Form to permanently bake all field values into the page and download your secure PDF." },
      ]
    },
    faqs: [
      { question: "What does flattening a PDF form do?", answer: "Flattening takes interactive form widgets (text inputs, checkboxes, dropdowns, signatures) and permanently draws their visible values into the page content stream, removing the interactive field layer so entries cannot be altered." },
      { question: "Can flattened form fields be edited or changed later?", answer: "No. Once flattened, form fields become static page graphics and cannot be edited with standard PDF form filler software." },
      { question: "What happens to digital signatures when flattening?", answer: "The visual appearance of any placed signature is preserved on the page, but the cryptographic digital signature container is removed because the document content stream is modified." },
      { question: "Does this tool support Adobe XFA forms?", answer: "Standard AcroForm PDF forms are fully supported. Proprietary XML-based Adobe XFA forms cannot be flattened directly in the browser; use Adobe Acrobat or print to PDF for XFA files." },
      { question: "Are my sensitive forms uploaded to external cloud servers?", answer: "No. KissThePDF flattens your PDF locally inside your browser memory using WebAssembly. Your confidential financial and personal data never leaves your device." },
    ],
    relatedTools: ["add-checkbox", "add-text-field", "add-radio-button", "fill-pdf-forms", "edit-pdf-metadata", "lock-pdf"],
  },

  // ==========================================
  // Category 7: Enhancement (9 Tools)
  // ==========================================
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add customizable page numbers to top or bottom margins.",
    category: "Enhancement",
    href: "/page-numbers",
    icon: "ListOrdered",
    status: "implemented",
    seoTitle: "Add Page Numbers to PDF Online",
    seoDescription: "Number PDF pages with custom position, font, and format options.",
    keywords: ["page numbers pdf", "add page numbers to pdf"],
  },
  {
    id: "header-footer",
    name: "Header & Footer",
    description: "Add headers and footers with custom text or page numbers.",
    category: "Enhancement",
    href: "/header-footer",
    icon: "AlignVerticalSpaceAround",
    status: "implemented",
    seoTitle: "Add Header & Footer to PDF",
    seoDescription: "Add custom text, dates, and page counts to headers and footers.",
    keywords: ["header footer pdf", "add header to pdf"],
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add text or image watermarks across PDF document pages.",
    category: "Enhancement",
    href: "/watermark-pdf",
    icon: "Droplets",
    status: "implemented",
    seoTitle: "Add Watermark to PDF Online",
    seoDescription: "Stamp custom text or logo image watermarks on PDF pages.",
    keywords: ["watermark pdf", "add watermark to pdf"],
    seoH1: "Watermark PDF Online Free",
    seoH2s: ["How to Watermark PDF", "Related Tools"],
    introParagraph: "Easily watermark pdf directly in your browser. Our free tool provides a fast, secure, and private way to process your files without any uploads.",
    howTo: {
      name: "How to Watermark PDF",
      description: "Learn how to watermark pdf in a few simple steps.",
      steps: [
        { name: "Upload File", text: "Select your file or drag and drop it into the tool." },
        { name: "Adjust Settings", text: "Choose your preferred options for processing." },
        { name: "Download", text: "Click to process and instantly download your new file." }
      ]
    },
    faqs: [
      { question: "Is this Watermark PDF tool free?", answer: "Yes, it is completely free to use with no hidden limits." },
      { question: "Are my files secure?", answer: "Yes, all processing happens locally in your browser. Your files are never uploaded to any server." }
    ],
    relatedTools: ["merge-pdf", "split-pdf", "compress-pdf"],
  },
  {
    id: "remove-watermark",
    name: "Remove Watermark",
    description: "Remove text or image watermark layers from PDF pages.",
    category: "Enhancement",
    href: "/remove-watermark",
    icon: "Droplets",
    status: "implemented",
    seoTitle: "Remove Watermark from PDF",
    seoDescription: "Remove watermark overlay elements from PDF document pages.",
    keywords: ["remove watermark pdf"],
  },
  {
    id: "bookmarks",
    name: "Bookmarks",
    description: "Create outline bookmarks for fast document navigation.",
    category: "Enhancement",
    href: "/bookmarks",
    icon: "Bookmark",
    status: "implemented",
    seoTitle: "Add Bookmarks to PDF Document",
    seoDescription: "Create outline bookmarks and chapter links in PDF files.",
    keywords: ["pdf bookmarks", "add bookmarks pdf"],
  },
  {
    id: "edit-bookmarks",
    name: "Edit Bookmarks",
    description: "Edit or reorganize existing PDF outline bookmarks.",
    category: "Enhancement",
    href: "/edit-bookmarks",
    icon: "BookmarkPlus",
    status: "implemented",
    seoTitle: "Edit PDF Bookmarks & Outline",
    seoDescription: "Modify, rename, or delete existing PDF outline bookmarks.",
    keywords: ["edit bookmarks pdf"],
  },
  {
    id: "table-of-contents",
    name: "Table of Contents",
    description: "Generate a hyperlinked Table of Contents page for your PDF.",
    category: "Enhancement",
    href: "/table-of-contents",
    icon: "Table",
    status: "implemented",
    seoTitle: "Generate PDF Table of Contents",
    seoDescription: "Generate a hyperlinked Table of Contents page from headings.",
    keywords: ["table of contents pdf", "pdf index"],
  },
  {
    id: "add-hyperlinks",
    name: "Add Hyperlinks",
    description: "Add clickable web URLs or internal page jump links to PDF pages.",
    category: "Enhancement",
    href: "/add-hyperlinks",
    icon: "Link",
    status: "implemented",
    seoTitle: "Add Clickable Hyperlinks to PDF",
    seoDescription: "Add clickable URL links and internal page jump links onto PDF pages.",
    keywords: ["add link to pdf", "hyperlink pdf"],
  },
  {
    id: "extract-links",
    name: "Extract Links",
    description: "Scan and extract all embedded web links and URLs from a PDF.",
    category: "Enhancement",
    href: "/extract-links",
    icon: "ExternalLink",
    status: "implemented",
    seoTitle: "Extract URLs & Links from PDF",
    seoDescription: "Extract all embedded web hyperlinks from inside a PDF document.",
    keywords: ["extract links pdf", "find urls pdf"],
  },

  // ==========================================
  // Category 8: Reading & Utilities (6 Tools)
  // ==========================================
  {
    id: "add-qr-code",
    name: "Add QR Code",
    description: "Generate and insert scannable QR codes onto PDF pages.",
    category: "Reading",
    href: "/add-qr-code",
    icon: "QrCode",
    status: "implemented",
    seoTitle: "Add QR Code to PDF Page",
    seoDescription: "Generate scannable QR codes pointing to URLs or text and stamp onto PDF.",
    keywords: ["add qr code to pdf", "stamp qr code"],
  },
  {
    id: "pdf-reader",
    name: "PDF Reader",
    description: "Fast, distraction-free browser PDF viewer with thumbnail navigation.",
    category: "Reading",
    href: "/pdf-reader",
    icon: "BookOpen",
    status: "implemented",
    seoTitle: "Free Browser PDF Reader",
    seoDescription: "Read PDF files directly in your browser with zoom and thumbnail navigation.",
    keywords: ["pdf reader online", "view pdf browser"],
  },
  {
    id: "fullscreen-pdf",
    name: "Fullscreen PDF",
    description: "Read PDFs in a clean, distraction-free fullscreen presentation mode.",
    category: "Reading",
    href: "/fullscreen-pdf",
    icon: "Maximize",
    status: "implemented",
    seoTitle: "Fullscreen PDF Viewer",
    seoDescription: "View PDFs in full-screen reader mode.",
    keywords: ["fullscreen pdf", "pdf presentation"],
  },
  {
    id: "pdf-search",
    name: "PDF Search",
    description: "Search and highlight text keywords across all pages of a PDF.",
    category: "Reading",
    href: "/pdf-search",
    icon: "Search",
    status: "implemented",
    seoTitle: "Search Text Inside PDF Online",
    seoDescription: "Search text keywords across PDF pages with instant match highlighting.",
    keywords: ["search text in pdf", "pdf search tool"],
  },
  {
    id: "pdf-presentation",
    name: "PDF Presentation",
    description: "Present PDF slides in fullscreen with slide controls.",
    category: "Reading",
    href: "/pdf-presentation",
    icon: "MonitorPlay",
    status: "implemented",
    seoTitle: "PDF Slide Presentation Mode",
    seoDescription: "Present PDF document pages as slides with keyboard presentation controls.",
    keywords: ["pdf presentation", "present pdf slides"],
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality.",
    category: "Reading",
    href: "/compress-pdf",
    icon: "Minimize",
    status: "implemented",
    seoTitle: "Compress PDF Online Free (Reduce File Size)",
    seoDescription: "Reduce PDF file size while preserving document quality. Free browser-based compression with zero server uploads, no file size caps, and instant download.",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf online", "compress pdf free", "compress pdf to 100kb", "compress pdf to 200kb", "reduce pdf file size without losing quality"],
    seoH1: "Compress PDF Online Free",
    seoH2s: ["How to Compress PDF Files Online", "Frequently Asked Questions", "Related Tools"],
    introParagraph: "Shrink large PDF documents and reduce file sizes significantly without sacrificing text sharpness or visual image clarity. KissThePDF utilizes advanced browser-based stream optimization, font deduplication, and WebAssembly compression algorithms to strip redundant metadata and optimize uncompressed object streams. Whether you need to reduce a multi-megabyte PDF for email attachment limits, compress scanned documents for government job portals, or meet strict online application thresholds (such as 100KB, 200KB, or 500KB limits on university and exam portals), KissThePDF delivers fast, balanced optimization. Because our compression engine runs 100% locally on your device, your private financial records, corporate presentations, and personal tax returns are never uploaded to external servers. Compress unlimited PDF files with no daily task caps, no watermarks, and no account sign-up needed. Achieve optimal document compression while preserving vector fonts and crisp graphical clarity for viewing and printing. Compare original and compressed file sizes in real time before downloading your optimized file.",
    howTo: {
      name: "How to Compress a PDF to Reduce File Size",
      description: "Optimize and reduce your PDF file size in 3 simple steps.",
      steps: [
        { name: "Upload PDF Document", text: "Drop your PDF file into the Compress PDF tool." },
        { name: "Select Compression Level", text: "Choose your desired compression balance (Recommended, Maximum Compression, or Low Compression)." },
        { name: "Compress and Download", text: "Click Compress PDF to view file size savings and download your optimized document." },
      ]
    },
    faqs: [
      { question: "How much can this tool reduce my PDF file size?", answer: "Depending on whether your PDF contains high-resolution scanned images or uncompressed object streams, file size reductions often range from 30% to 80%." },
      { question: "Will compressing my PDF blur the text or reduce readability?", answer: "No. KissThePDF optimizes the internal PDF structure and font streams without degrading the vector quality of your text." },
      { question: "Can I compress a PDF to meet portal upload limits (like 100KB or 200KB)?", answer: "Yes. The compression engine significantly reduces file weight to help documents meet strict online application, exam form, and portal upload thresholds." },
      { question: "Is there a limit on the input PDF size?", answer: "No. Because processing is executed client-side using your computer hardware, you can compress large multi-megabyte PDFs without server timeout errors." },
      { question: "Are my files uploaded to any remote server?", answer: "No. All PDF optimization is performed locally in your web browser. Your confidential documents remain strictly on your device." },
    ],
    relatedTools: ["merge-pdf", "pdf-to-jpg", "crop-pdf", "scale-pdf", "flatten-pdf-form"],
  },
];

export const getToolsByCategory = (): Record<string, ToolDefinition[]> => {
  return tools.reduce((acc, tool) => {
    if (!acc[tool.category]) {
      acc[tool.category] = [];
    }
    acc[tool.category].push(tool);
    return acc;
  }, {} as Record<string, ToolDefinition[]>);
};
