import { ToolDefinition } from "@/types";

export const tools: ToolDefinition[] = [
  // ==========================================
  // Category 1: Organization (10 Tools)
  // ==========================================
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one unified document.",
    category: "Organization",
    href: "/merge-pdf",
    icon: "Combine",
    status: "placeholder",
    seoTitle: "Merge PDF Files Online for Free | Kiss the PDF",
    seoDescription: "Combine multiple PDF files into one document directly in your browser. Free, private, and easy to use.",
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger free"],
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Separate pages or page ranges from a PDF into independent files.",
    category: "Organization",
    href: "/split-pdf",
    icon: "SplitSquareHorizontal",
    status: "placeholder",
    seoTitle: "Split PDF Pages Online for Free | Kiss the PDF",
    seoDescription: "Extract pages from your PDF or split a document into multiple files directly in your browser.",
    keywords: ["split pdf", "extract pdf pages", "cut pdf", "separate pdf"],
  },
  {
    id: "extract-pdf-pages",
    name: "Extract Pages",
    description: "Create a new PDF containing only selected pages.",
    category: "Organization",
    href: "/extract-pdf-pages",
    icon: "FileOutput",
    status: "placeholder",
    seoTitle: "Extract Pages from PDF Online | Kiss the PDF",
    seoDescription: "Extract selected pages from a PDF into a new document directly in your browser.",
    keywords: ["extract pdf pages", "extract pages from pdf", "pull pages from pdf"],
  },
  {
    id: "delete-pdf-pages",
    name: "Delete Pages",
    description: "Remove unwanted pages from your PDF securely.",
    category: "Organization",
    href: "/delete-pdf-pages",
    icon: "Trash2",
    status: "placeholder",
    seoTitle: "Delete PDF Pages Online for Free | Kiss the PDF",
    seoDescription: "Easily select and remove specific pages from your PDF document without server upload.",
    keywords: ["delete pdf pages", "remove pdf pages", "delete page from pdf"],
  },
  {
    id: "reorder-pages",
    name: "Reorder Pages",
    description: "Rearrange PDF pages into any custom sequence.",
    category: "Organization",
    href: "/reorder-pages",
    icon: "ArrowUpDown",
    status: "placeholder",
    seoTitle: "Reorder PDF Pages Free Online | Kiss the PDF",
    seoDescription: "Rearrange page order in any PDF with simple visual drag and drop.",
    keywords: ["reorder pdf pages", "rearrange pdf", "sort pdf pages"],
  },
  {
    id: "duplicate-pages",
    name: "Duplicate Pages",
    description: "Duplicate selected pages within a PDF document.",
    category: "Organization",
    href: "/duplicate-pages",
    icon: "Copy",
    status: "placeholder",
    seoTitle: "Duplicate PDF Pages Free | Kiss the PDF",
    seoDescription: "Duplicate any page or set of pages within a PDF document.",
    keywords: ["duplicate pdf pages", "copy pdf page"],
  },
  {
    id: "insert-blank-page",
    name: "Insert Blank Page",
    description: "Insert a clean blank page anywhere inside a PDF document.",
    category: "Organization",
    href: "/insert-blank-page",
    icon: "FilePlus",
    status: "placeholder",
    seoTitle: "Insert Blank Page into PDF | Kiss the PDF",
    seoDescription: "Add blank pages to your PDF document at specific page positions.",
    keywords: ["insert blank page pdf", "add empty page to pdf"],
  },
  {
    id: "insert-pdf-pages",
    name: "Insert PDF Pages",
    description: "Insert pages from another PDF into your document.",
    category: "Organization",
    href: "/insert-pdf-pages",
    icon: "FileInput",
    status: "placeholder",
    seoTitle: "Insert PDF Pages Online | Kiss the PDF",
    seoDescription: "Combine pages from external PDFs directly into target page positions.",
    keywords: ["insert pages into pdf", "add pages from pdf"],
  },
  {
    id: "move-pages-between-pdfs",
    name: "Move Pages Between PDFs",
    description: "Select and transfer pages between multiple PDF documents.",
    category: "Organization",
    href: "/move-pages-between-pdfs",
    icon: "ArrowLeftRight",
    status: "placeholder",
    seoTitle: "Move Pages Between PDFs | Kiss the PDF",
    seoDescription: "Transfer selected pages interactively between multiple PDF files.",
    keywords: ["move pages between pdfs", "transfer pdf pages"],
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    description: "Complete page manager to reorder, delete, rotate, and duplicate pages.",
    category: "Organization",
    href: "/organize-pdf",
    icon: "LayoutGrid",
    status: "placeholder",
    seoTitle: "Organize PDF Pages Free | Kiss the PDF",
    seoDescription: "All-in-one visual page manager to rearrange, rotate, duplicate, and delete PDF pages.",
    keywords: ["organize pdf", "manage pdf pages"],
  },

  // ==========================================
  // Category 2: Pages (20 Tools)
  // ==========================================
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate individual PDF pages or the entire document.",
    category: "Pages",
    href: "/rotate-pdf",
    icon: "RotateCw",
    status: "placeholder",
    seoTitle: "Rotate PDF Pages Online | Kiss the PDF",
    seoDescription: "Rotate individual PDF pages or the entire document with visual page previews.",
    keywords: ["rotate pdf", "turn pdf", "change pdf orientation"],
  },
  {
    id: "rotate-entire-pdf",
    name: "Rotate Entire PDF",
    description: "Rotate every page in a PDF document by 90°, 180°, or 270°.",
    category: "Pages",
    href: "/rotate-entire-pdf",
    icon: "RotateCcw",
    status: "placeholder",
    seoTitle: "Rotate Entire PDF Document | Kiss the PDF",
    seoDescription: "Batch rotate all pages in your PDF document simultaneously.",
    keywords: ["rotate all pdf pages", "rotate document"],
  },
  {
    id: "crop-pdf",
    name: "Crop PDF",
    description: "Crop margins or specific rectangular areas from PDF pages.",
    category: "Pages",
    href: "/crop-pdf",
    icon: "Crop",
    status: "placeholder",
    seoTitle: "Crop PDF Pages Free Online | Kiss the PDF",
    seoDescription: "Trim page margins or crop specific areas of your PDF pages.",
    keywords: ["crop pdf", "trim pdf margins", "cut pdf page"],
  },
  {
    id: "resize-pdf",
    name: "Resize PDF",
    description: "Change PDF page dimensions to standard or custom sizes.",
    category: "Pages",
    href: "/resize-pdf",
    icon: "Maximize2",
    status: "placeholder",
    seoTitle: "Resize PDF Page Dimensions | Kiss the PDF",
    seoDescription: "Resize PDF page dimensions to standard formats or custom width/height.",
    keywords: ["resize pdf", "change pdf page size"],
  },
  {
    id: "change-page-orientation",
    name: "Change Page Orientation",
    description: "Convert pages between Portrait and Landscape orientations.",
    category: "Pages",
    href: "/change-page-orientation",
    icon: "Smartphone",
    status: "placeholder",
    seoTitle: "Change PDF Page Orientation | Kiss the PDF",
    seoDescription: "Toggle PDF pages between landscape and portrait orientation.",
    keywords: ["pdf landscape to portrait", "change page orientation"],
  },
  {
    id: "change-page-size",
    name: "Change Page Size",
    description: "Adjust PDF pages to standard paper formats (A4, Letter, Legal).",
    category: "Pages",
    href: "/change-page-size",
    icon: "Ratio",
    status: "placeholder",
    seoTitle: "Change PDF Page Format | Kiss the PDF",
    seoDescription: "Change document pages to standard paper formats.",
    keywords: ["change page size pdf", "convert pdf size"],
  },
  {
    id: "a4-pdf",
    name: "A4 PDF",
    description: "Standardize all PDF pages to standard A4 format (210 x 297 mm).",
    category: "Pages",
    href: "/a4-pdf",
    icon: "FileText",
    status: "placeholder",
    seoTitle: "Convert PDF to A4 Size | Kiss the PDF",
    seoDescription: "Resize and adjust PDF page content to standard A4 paper size.",
    keywords: ["a4 pdf", "convert pdf to a4"],
  },
  {
    id: "a3-pdf",
    name: "A3 PDF",
    description: "Standardize PDF pages to A3 paper format (297 x 420 mm).",
    category: "Pages",
    href: "/a3-pdf",
    icon: "FileText",
    status: "placeholder",
    seoTitle: "Convert PDF to A3 Size | Kiss the PDF",
    seoDescription: "Resize PDF pages to large format A3 size.",
    keywords: ["a3 pdf", "convert pdf to a3"],
  },
  {
    id: "letter-pdf",
    name: "Letter PDF",
    description: "Standardize PDF pages to US Letter format (8.5 x 11 in).",
    category: "Pages",
    href: "/letter-pdf",
    icon: "FileText",
    status: "placeholder",
    seoTitle: "Convert PDF to US Letter Size | Kiss the PDF",
    seoDescription: "Convert document pages to US Letter standard paper dimensions.",
    keywords: ["letter size pdf", "us letter pdf"],
  },
  {
    id: "legal-pdf",
    name: "Legal PDF",
    description: "Standardize PDF pages to US Legal format (8.5 x 14 in).",
    category: "Pages",
    href: "/legal-pdf",
    icon: "FileText",
    status: "placeholder",
    seoTitle: "Convert PDF to US Legal Size | Kiss the PDF",
    seoDescription: "Format document pages to US Legal paper dimensions.",
    keywords: ["legal size pdf", "us legal pdf"],
  },
  {
    id: "custom-page-size",
    name: "Custom Page Size",
    description: "Set exact custom width and height dimensions for PDF pages.",
    category: "Pages",
    href: "/custom-page-size",
    icon: "Ruler",
    status: "placeholder",
    seoTitle: "Custom PDF Page Dimensions | Kiss the PDF",
    seoDescription: "Define exact custom dimensions in mm, inches, or points for PDF pages.",
    keywords: ["custom pdf page size", "set pdf width height"],
  },
  {
    id: "add-margins",
    name: "Add Margins",
    description: "Add white outer padding/margins around document pages.",
    category: "Pages",
    href: "/add-margins",
    icon: "Square",
    status: "placeholder",
    seoTitle: "Add Margins to PDF Pages | Kiss the PDF",
    seoDescription: "Add uniform or custom margins around page content for printing.",
    keywords: ["add margins to pdf", "pdf page padding"],
  },
  {
    id: "remove-margins",
    name: "Remove Margins",
    description: "Trim unnecessary whitespace margins around PDF pages.",
    category: "Pages",
    href: "/remove-margins",
    icon: "Minimize2",
    status: "placeholder",
    seoTitle: "Remove PDF Margins | Kiss the PDF",
    seoDescription: "Trim outer whitespace margins to maximize printable page area.",
    keywords: ["remove pdf margins", "crop white space pdf"],
  },
  {
    id: "center-page-content",
    name: "Center Page Content",
    description: "Automatically center page content inside printable boundaries.",
    category: "Pages",
    href: "/center-page-content",
    icon: "AlignCenter",
    status: "placeholder",
    seoTitle: "Center Content on PDF Pages | Kiss the PDF",
    seoDescription: "Center page content horizontally and vertically on PDF pages.",
    keywords: ["center pdf content", "align pdf page"],
  },
  {
    id: "fit-content-to-page",
    name: "Fit Content to Page",
    description: "Scale page content to fit within target page margins cleanly.",
    category: "Pages",
    href: "/fit-content-to-page",
    icon: "Shrink",
    status: "placeholder",
    seoTitle: "Fit Content to PDF Page Size | Kiss the PDF",
    seoDescription: "Automatically scale page elements to fit inside standard margins.",
    keywords: ["fit to page pdf", "scale content pdf"],
  },
  {
    id: "scale-pdf",
    name: "Scale PDF",
    description: "Scale PDF page content up or down by percentage.",
    category: "Pages",
    href: "/scale-pdf",
    icon: "Expand",
    status: "placeholder",
    seoTitle: "Scale PDF Pages Up or Down | Kiss the PDF",
    seoDescription: "Proportionally scale page content up or down by custom percentage.",
    keywords: ["scale pdf", "zoom pdf content"],
  },
  {
    id: "reverse-pages",
    name: "Reverse Pages",
    description: "Reverse the order of pages in a document (last page first).",
    category: "Pages",
    href: "/reverse-pages",
    icon: "ArrowDownUp",
    status: "placeholder",
    seoTitle: "Reverse PDF Page Order | Kiss the PDF",
    seoDescription: "Reverse page sequence so the last page comes first.",
    keywords: ["reverse page order pdf", "invert pdf pages"],
  },
  {
    id: "remove-blank-pages",
    name: "Remove Blank Pages",
    description: "Detect and remove empty or blank pages from a PDF.",
    category: "Pages",
    href: "/remove-blank-pages",
    icon: "Eraser",
    status: "placeholder",
    seoTitle: "Remove Blank Pages from PDF | Kiss the PDF",
    seoDescription: "Automatically identify and delete blank or empty pages from PDFs.",
    keywords: ["remove blank pages pdf", "delete empty pages"],
  },
  {
    id: "extract-odd-pages",
    name: "Extract Odd Pages",
    description: "Create a new document containing only odd-numbered pages (1, 3, 5...).",
    category: "Pages",
    href: "/extract-odd-pages",
    icon: "Hash",
    status: "placeholder",
    seoTitle: "Extract Odd Pages from PDF | Kiss the PDF",
    seoDescription: "Extract odd-numbered pages into an independent PDF document.",
    keywords: ["extract odd pages pdf", "odd pages pdf"],
  },
  {
    id: "extract-even-pages",
    name: "Extract Even Pages",
    description: "Create a new document containing only even-numbered pages (2, 4, 6...).",
    category: "Pages",
    href: "/extract-even-pages",
    icon: "Hash",
    status: "placeholder",
    seoTitle: "Extract Even Pages from PDF | Kiss the PDF",
    seoDescription: "Extract even-numbered pages into an independent PDF document.",
    keywords: ["extract even pages pdf", "even pages pdf"],
  },

  // ==========================================
  // Category 3: Convert (16 Tools)
  // ==========================================
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG images into a single clean PDF document.",
    category: "Convert",
    href: "/jpg-to-pdf",
    icon: "FileImage",
    status: "placeholder",
    seoTitle: "Convert JPG to PDF Free Online | Kiss the PDF",
    seoDescription: "Convert JPG and JPEG images into a single PDF document in your browser.",
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf"],
  },
  {
    id: "png-to-pdf",
    name: "PNG to PDF",
    description: "Convert PNG images into a PDF document with transparency support.",
    category: "Convert",
    href: "/png-to-pdf",
    icon: "Image",
    status: "placeholder",
    seoTitle: "Convert PNG to PDF Online Free | Kiss the PDF",
    seoDescription: "Convert PNG graphics into PDF documents with custom page margins.",
    keywords: ["png to pdf", "image to pdf"],
  },
  {
    id: "webp-to-pdf",
    name: "WebP to PDF",
    description: "Convert WebP images into a high quality PDF document.",
    category: "Convert",
    href: "/webp-to-pdf",
    icon: "Image",
    status: "placeholder",
    seoTitle: "Convert WebP to PDF Free | Kiss the PDF",
    seoDescription: "Convert WebP images directly into PDF documents in your browser.",
    keywords: ["webp to pdf", "convert webp to pdf"],
  },
  {
    id: "gif-to-pdf",
    name: "GIF to PDF",
    description: "Convert static or animated GIF frames into a PDF.",
    category: "Convert",
    href: "/gif-to-pdf",
    icon: "Image",
    status: "placeholder",
    seoTitle: "Convert GIF to PDF Free | Kiss the PDF",
    seoDescription: "Convert GIF image frames into PDF document pages.",
    keywords: ["gif to pdf", "convert gif to pdf"],
  },
  {
    id: "bmp-to-pdf",
    name: "BMP to PDF",
    description: "Convert bitmap images into standard PDF files.",
    category: "Convert",
    href: "/bmp-to-pdf",
    icon: "Image",
    status: "placeholder",
    seoTitle: "Convert BMP to PDF Free | Kiss the PDF",
    seoDescription: "Convert BMP bitmap images into clean PDF documents.",
    keywords: ["bmp to pdf", "bitmap to pdf"],
  },
  {
    id: "tiff-to-pdf",
    name: "TIFF to PDF",
    description: "Convert single or multi-page TIFF images into PDF documents.",
    category: "Convert",
    href: "/tiff-to-pdf",
    icon: "Image",
    status: "placeholder",
    seoTitle: "Convert TIFF to PDF Free | Kiss the PDF",
    seoDescription: "Convert single or multi-frame TIFF images into PDF files.",
    keywords: ["tiff to pdf", "tif to pdf"],
  },
  {
    id: "svg-to-pdf",
    name: "SVG to PDF",
    description: "Convert SVG vector graphics into scalable PDF pages.",
    category: "Convert",
    href: "/svg-to-pdf",
    icon: "PenTool",
    status: "placeholder",
    seoTitle: "Convert SVG Vector to PDF | Kiss the PDF",
    seoDescription: "Render vector SVG graphics into crisp vector PDF documents.",
    keywords: ["svg to pdf", "vector to pdf"],
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine multiple images of any format into one PDF.",
    category: "Convert",
    href: "/images-to-pdf",
    icon: "Images",
    status: "placeholder",
    seoTitle: "Combine Images to PDF | Kiss the PDF",
    seoDescription: "Merge multiple images of different formats (JPG, PNG, WebP) into a single PDF.",
    keywords: ["images to pdf", "combine pictures to pdf"],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages into high quality JPG images.",
    category: "Convert",
    href: "/pdf-to-jpg",
    icon: "ImageDown",
    status: "placeholder",
    seoTitle: "Convert PDF to JPG Online | Kiss the PDF",
    seoDescription: "Convert PDF pages into high quality JPG images in your browser.",
    keywords: ["pdf to jpg", "pdf to jpeg", "convert pdf to image"],
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert PDF pages to lossless PNG images.",
    category: "Convert",
    href: "/pdf-to-png",
    icon: "ImageDown",
    status: "placeholder",
    seoTitle: "Convert PDF to PNG Online | Kiss the PDF",
    seoDescription: "Convert PDF pages to lossless PNG images with customizable resolution.",
    keywords: ["pdf to png", "convert pdf to png"],
  },
  {
    id: "pdf-to-webp",
    name: "PDF to WebP",
    description: "Convert PDF pages to WebP images with adjustable quality.",
    category: "Convert",
    href: "/pdf-to-webp",
    icon: "ImageDown",
    status: "placeholder",
    seoTitle: "Convert PDF to WebP Online | Kiss the PDF",
    seoDescription: "Convert PDF pages to modern WebP images directly in your browser.",
    keywords: ["pdf to webp", "convert pdf to webp"],
  },
  {
    id: "pdf-to-tiff",
    name: "PDF to TIFF",
    description: "Convert PDF document pages to uncompressed or compressed TIFF images.",
    category: "Convert",
    href: "/pdf-to-tiff",
    icon: "ImageDown",
    status: "placeholder",
    seoTitle: "Convert PDF to TIFF Free | Kiss the PDF",
    seoDescription: "Convert PDF document pages to TIFF image format.",
    keywords: ["pdf to tiff", "convert pdf to tif"],
  },
  {
    id: "pdf-to-images-zip",
    name: "PDF to Images ZIP",
    description: "Export all PDF pages as images inside a single ZIP archive.",
    category: "Convert",
    href: "/pdf-to-images-zip",
    icon: "FileArchive",
    status: "placeholder",
    seoTitle: "Export PDF Pages to ZIP Images | Kiss the PDF",
    seoDescription: "Export every page of a PDF as individual image files bundled in a ZIP archive.",
    keywords: ["pdf to zip images", "export pdf pages zip"],
  },
  {
    id: "extract-images-from-pdf",
    name: "Extract Images from PDF",
    description: "Extract embedded bitmap images from inside a PDF document.",
    category: "Convert",
    href: "/extract-images-from-pdf",
    icon: "ScanLine",
    status: "placeholder",
    seoTitle: "Extract Embedded Images from PDF | Kiss the PDF",
    seoDescription: "Extract original embedded images contained inside your PDF document.",
    keywords: ["extract images from pdf", "rip images pdf"],
  },
  {
    id: "photo-album-pdf",
    name: "Photo Album PDF",
    description: "Format multiple photos into a photo album PDF layout.",
    category: "Convert",
    href: "/photo-album-pdf",
    icon: "BookImage",
    status: "placeholder",
    seoTitle: "Create Photo Album PDF | Kiss the PDF",
    seoDescription: "Format photo collections into a clean PDF photo album with custom frames.",
    keywords: ["photo album pdf", "make photo book pdf"],
  },
  {
    id: "contact-sheet-pdf",
    name: "Contact Sheet PDF",
    description: "Create a thumbnail grid contact sheet PDF from multiple images.",
    category: "Convert",
    href: "/contact-sheet-pdf",
    icon: "Grid3x3",
    status: "placeholder",
    seoTitle: "Create Image Contact Sheet PDF | Kiss the PDF",
    seoDescription: "Organize image thumbnails into a structured contact sheet PDF.",
    keywords: ["contact sheet pdf", "image grid pdf"],
  },

  // ==========================================
  // Category 4: Edit (18 Tools)
  // ==========================================
  {
    id: "edit-pdf",
    name: "Edit PDF",
    description: "Interactive PDF editor to add text, drawings, shapes, and annotations.",
    category: "Edit",
    href: "/edit-pdf",
    icon: "Pencil",
    status: "placeholder",
    seoTitle: "Edit PDF Files Online | Kiss the PDF",
    seoDescription: "Interactive PDF editor to add text, drawings, signatures, shapes, and markups.",
    keywords: ["edit pdf", "online pdf editor", "modify pdf"],
  },
  {
    id: "add-text",
    name: "Add Text",
    description: "Place text overlays, titles, and paragraphs anywhere on PDF pages.",
    category: "Edit",
    href: "/add-text",
    icon: "Type",
    status: "placeholder",
    seoTitle: "Add Text to PDF Online | Kiss the PDF",
    seoDescription: "Place new text blocks onto PDF pages with custom font sizes and colors.",
    keywords: ["add text to pdf", "write on pdf"],
  },
  {
    id: "add-image",
    name: "Add Image",
    description: "Insert and position images or logos onto PDF document pages.",
    category: "Edit",
    href: "/add-image",
    icon: "ImagePlus",
    status: "placeholder",
    seoTitle: "Insert Image into PDF | Kiss the PDF",
    seoDescription: "Insert image logos or photos onto specific page coordinates.",
    keywords: ["insert image in pdf", "add picture to pdf"],
  },
  {
    id: "add-shape",
    name: "Add Shape",
    description: "Insert rectangles, circles, arrows, and custom shapes into PDFs.",
    category: "Edit",
    href: "/add-shape",
    icon: "Shapes",
    status: "placeholder",
    seoTitle: "Add Shapes to PDF | Kiss the PDF",
    seoDescription: "Add geometric shapes and callout boxes onto PDF pages.",
    keywords: ["add shape to pdf", "draw shapes pdf"],
  },
  {
    id: "draw-on-pdf",
    name: "Draw on PDF",
    description: "Freehand drawing tool with pen width and color controls.",
    category: "Edit",
    href: "/draw-on-pdf",
    icon: "PenLine",
    status: "placeholder",
    seoTitle: "Draw on PDF Pages Free | Kiss the PDF",
    seoDescription: "Draw freehand lines, sketches, and notes on PDF document pages.",
    keywords: ["draw on pdf", "freehand pdf"],
  },
  {
    id: "pen-tool",
    name: "Pen Tool",
    description: "Precision pen tool for smooth freehand drawing and sketching.",
    category: "Edit",
    href: "/pen-tool",
    icon: "Pen",
    status: "placeholder",
    seoTitle: "PDF Pen Drawing Tool | Kiss the PDF",
    seoDescription: "Smooth vector pen tool for freehand notes and illustrations on PDFs.",
    keywords: ["pen tool pdf", "sketch on pdf"],
  },
  {
    id: "eraser",
    name: "Eraser",
    description: "Erase drawings, shapes, or added text overlays from PDF pages.",
    category: "Edit",
    href: "/eraser",
    icon: "Eraser",
    status: "placeholder",
    seoTitle: "PDF Eraser Tool | Kiss the PDF",
    seoDescription: "Erase added annotations, drawings, and shapes from PDF pages.",
    keywords: ["pdf eraser", "erase notes pdf"],
  },
  {
    id: "highlight-pdf",
    name: "Highlight PDF",
    description: "Highlight text and key sections with translucent highlighter colors.",
    category: "Edit",
    href: "/highlight-pdf",
    icon: "Highlighter",
    status: "placeholder",
    seoTitle: "Highlight PDF Text Online | Kiss the PDF",
    seoDescription: "Highlight text lines and paragraphs with translucent color overlays.",
    keywords: ["highlight pdf", "pdf text highlighter"],
  },
  {
    id: "underline-pdf",
    name: "Underline PDF",
    description: "Add underline annotations to document text.",
    category: "Edit",
    href: "/underline-pdf",
    icon: "Underline",
    status: "placeholder",
    seoTitle: "Underline PDF Text | Kiss the PDF",
    seoDescription: "Add underline markup annotations to PDF document text.",
    keywords: ["underline text pdf", "markup pdf"],
  },
  {
    id: "strikethrough-pdf",
    name: "Strikethrough PDF",
    description: "Add strikethrough lines over PDF document text.",
    category: "Edit",
    href: "/strikethrough-pdf",
    icon: "Strikethrough",
    status: "placeholder",
    seoTitle: "Strikethrough PDF Text | Kiss the PDF",
    seoDescription: "Mark text with strikethrough annotations.",
    keywords: ["strikethrough pdf", "cross out text pdf"],
  },
  {
    id: "add-arrow",
    name: "Add Arrow",
    description: "Draw directional arrow pointers onto PDF document pages.",
    category: "Edit",
    href: "/add-arrow",
    icon: "ArrowRight",
    status: "placeholder",
    seoTitle: "Add Arrow Pointer to PDF | Kiss the PDF",
    seoDescription: "Insert directional arrows to point out key document details.",
    keywords: ["add arrow to pdf", "arrow annotation pdf"],
  },
  {
    id: "add-line",
    name: "Add Line",
    description: "Draw straight lines with custom stroke thickness and color.",
    category: "Edit",
    href: "/add-line",
    icon: "Minus",
    status: "placeholder",
    seoTitle: "Add Straight Line to PDF | Kiss the PDF",
    seoDescription: "Draw straight lines across PDF pages.",
    keywords: ["add line to pdf", "draw line pdf"],
  },
  {
    id: "add-rectangle",
    name: "Add Rectangle",
    description: "Draw rectangular boxes and frames on PDF pages.",
    category: "Edit",
    href: "/add-rectangle",
    icon: "Square",
    status: "placeholder",
    seoTitle: "Add Rectangle Box to PDF | Kiss the PDF",
    seoDescription: "Insert rectangular boxes with stroke and fill options.",
    keywords: ["add rectangle pdf", "draw box pdf"],
  },
  {
    id: "add-circle",
    name: "Add Circle",
    description: "Draw circular or elliptical annotation overlays.",
    category: "Edit",
    href: "/add-circle",
    icon: "Circle",
    status: "placeholder",
    seoTitle: "Add Circle Shape to PDF | Kiss the PDF",
    seoDescription: "Insert circular annotations onto PDF document pages.",
    keywords: ["add circle to pdf", "draw circle pdf"],
  },
  {
    id: "add-polygon",
    name: "Add Polygon",
    description: "Draw multi-point polygon shapes on PDF pages.",
    category: "Edit",
    href: "/add-polygon",
    icon: "Triangle",
    status: "placeholder",
    seoTitle: "Add Polygon Shape to PDF | Kiss the PDF",
    seoDescription: "Draw multi-sided custom polygon shapes on PDF pages.",
    keywords: ["add polygon pdf", "draw polygon"],
  },
  {
    id: "sticky-notes",
    name: "Sticky Notes",
    description: "Place yellow or custom sticky note comments on PDF pages.",
    category: "Edit",
    href: "/sticky-notes",
    icon: "StickyNote",
    status: "placeholder",
    seoTitle: "Add Sticky Notes to PDF | Kiss the PDF",
    seoDescription: "Attach pop-up sticky notes and comment callouts to document pages.",
    keywords: ["sticky notes pdf", "add notes to pdf"],
  },
  {
    id: "pdf-comments",
    name: "PDF Comments",
    description: "View and add text comments to document pages.",
    category: "Edit",
    href: "/pdf-comments",
    icon: "MessageSquare",
    status: "placeholder",
    seoTitle: "Add PDF Comments & Annotations | Kiss the PDF",
    seoDescription: "Add comment threads and text feedback to PDF pages.",
    keywords: ["pdf comments", "annotate pdf"],
  },
  {
    id: "whiteout-pdf",
    name: "Whiteout PDF",
    description: "Cover sensitive areas or text with a white opaque block.",
    category: "Edit",
    href: "/whiteout-pdf",
    icon: "Paintbrush",
    status: "placeholder",
    seoTitle: "Whiteout PDF Content | Kiss the PDF",
    seoDescription: "Cover sensitive information with an opaque whiteout overlay.",
    keywords: ["whiteout pdf", "hide text pdf", "redact pdf"],
  },

  // ==========================================
  // Category 5: Security (9 Tools)
  // ==========================================
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "Password protect your PDF with strong user and owner passwords.",
    category: "Security",
    href: "/protect-pdf",
    icon: "Lock",
    status: "placeholder",
    seoTitle: "Password Protect PDF Online | Kiss the PDF",
    seoDescription: "Add password encryption to restrict reading or modifying your PDF.",
    keywords: ["protect pdf", "password protect pdf", "lock pdf"],
  },
  {
    id: "remove-pdf-password",
    name: "Remove PDF Password",
    description: "Remove password protection from authorized PDF files.",
    category: "Security",
    href: "/remove-pdf-password",
    icon: "LockOpen",
    status: "placeholder",
    seoTitle: "Remove PDF Password Protection | Kiss the PDF",
    seoDescription: "Unlock password-protected PDF files when authorized.",
    keywords: ["remove pdf password", "unlock pdf"],
  },
  {
    id: "encrypt-pdf",
    name: "Encrypt PDF",
    description: "Encrypt document contents using standard AES encryption.",
    category: "Security",
    href: "/encrypt-pdf",
    icon: "Shield",
    status: "placeholder",
    seoTitle: "Encrypt PDF Files Online | Kiss the PDF",
    seoDescription: "Encrypt PDF files locally with strong encryption algorithms.",
    keywords: ["encrypt pdf", "pdf encryption"],
  },
  {
    id: "decrypt-pdf",
    name: "Decrypt PDF",
    description: "Decrypt encrypted PDF documents with password authorization.",
    category: "Security",
    href: "/decrypt-pdf",
    icon: "ShieldOff",
    status: "placeholder",
    seoTitle: "Decrypt PDF Files Online | Kiss the PDF",
    seoDescription: "Decrypt encrypted PDF files directly in your browser.",
    keywords: ["decrypt pdf", "pdf decryption"],
  },
  {
    id: "pdf-permissions",
    name: "PDF Permissions",
    description: "Manage printing, copying, editing, and comment permissions.",
    category: "Security",
    href: "/pdf-permissions",
    icon: "KeyRound",
    status: "placeholder",
    seoTitle: "Set PDF Document Permissions | Kiss the PDF",
    seoDescription: "Configure allowed actions for PDF files (printing, copying, editing).",
    keywords: ["pdf permissions", "restrict printing pdf"],
  },
  {
    id: "printing-permissions",
    name: "Printing Permissions",
    description: "Allow or prevent high-resolution printing of your PDF.",
    category: "Security",
    href: "/printing-permissions",
    icon: "Printer",
    status: "placeholder",
    seoTitle: "Control PDF Printing Permissions | Kiss the PDF",
    seoDescription: "Restrict or enable document printing rights.",
    keywords: ["disable printing pdf", "printing permissions"],
  },
  {
    id: "copy-permissions",
    name: "Copy Permissions",
    description: "Restrict text and image copying from document pages.",
    category: "Security",
    href: "/copy-permissions",
    icon: "Copy",
    status: "placeholder",
    seoTitle: "Restrict Text Copying in PDF | Kiss the PDF",
    seoDescription: "Prevent unauthorized copying of text and content from your PDF.",
    keywords: ["prevent copy pdf", "copy permissions"],
  },
  {
    id: "editing-permissions",
    name: "Editing Permissions",
    description: "Lock document pages to prevent modification or page extraction.",
    category: "Security",
    href: "/editing-permissions",
    icon: "FilePenLine",
    status: "placeholder",
    seoTitle: "Set PDF Editing Restrictions | Kiss the PDF",
    seoDescription: "Prevent unauthorized edits or page modifications in your PDF.",
    keywords: ["prevent editing pdf", "edit permissions"],
  },
  {
    id: "comment-permissions",
    name: "Comment Permissions",
    description: "Control whether readers can add annotations or fill forms.",
    category: "Security",
    href: "/comment-permissions",
    icon: "MessageCircle",
    status: "placeholder",
    seoTitle: "Control PDF Commenting Rights | Kiss the PDF",
    seoDescription: "Restrict or grant commenting and annotation privileges on your PDF.",
    keywords: ["comment permissions pdf"],
  },

  // ==========================================
  // Category 6: Forms (13 Tools)
  // ==========================================
  {
    id: "remove-pdf-metadata",
    name: "Remove PDF Metadata",
    description: "Strip author, title, creation date, and hidden metadata from PDF.",
    category: "Forms",
    href: "/remove-pdf-metadata",
    icon: "FileX",
    status: "placeholder",
    seoTitle: "Remove PDF Metadata & Properties | Kiss the PDF",
    seoDescription: "Strip hidden document author, title, keywords, and creation metadata.",
    keywords: ["remove pdf metadata", "clean pdf properties"],
  },
  {
    id: "edit-pdf-metadata",
    name: "Edit PDF Metadata",
    description: "Edit document Title, Author, Subject, Creator, and Keywords.",
    category: "Forms",
    href: "/edit-pdf-metadata",
    icon: "FileCog",
    status: "placeholder",
    seoTitle: "Edit PDF Title & Author Metadata | Kiss the PDF",
    seoDescription: "Modify document metadata fields like Title, Author, Subject, and Creator.",
    keywords: ["edit pdf metadata", "pdf title author"],
  },
  {
    id: "fill-pdf-forms",
    name: "Fill PDF Forms",
    description: "Fill interactive PDF form fields directly in the browser.",
    category: "Forms",
    href: "/fill-pdf-forms",
    icon: "ClipboardList",
    status: "placeholder",
    seoTitle: "Fill PDF Forms Online | Kiss the PDF",
    seoDescription: "Fill text fields, checkboxes, and radio buttons in PDF forms.",
    keywords: ["fill pdf form", "pdf form filler"],
  },
  {
    id: "add-text-field",
    name: "Add Text Field",
    description: "Place interactive text input fields onto a PDF form.",
    category: "Forms",
    href: "/add-text-field",
    icon: "TextCursor",
    status: "placeholder",
    seoTitle: "Add Interactive Text Field to PDF | Kiss the PDF",
    seoDescription: "Insert fillable text input fields onto PDF forms.",
    keywords: ["add text field pdf", "create form field"],
  },
  {
    id: "add-checkbox",
    name: "Add Checkbox",
    description: "Insert checkable box fields into PDF documents.",
    category: "Forms",
    href: "/add-checkbox",
    icon: "CheckSquare",
    status: "placeholder",
    seoTitle: "Add Checkbox to PDF Form | Kiss the PDF",
    seoDescription: "Insert interactive checkable box fields into forms.",
    keywords: ["add checkbox pdf", "interactive checkbox"],
  },
  {
    id: "add-radio-button",
    name: "Add Radio Button",
    description: "Insert single-choice radio button groups into PDF forms.",
    category: "Forms",
    href: "/add-radio-button",
    icon: "CircleDot",
    status: "placeholder",
    seoTitle: "Add Radio Buttons to PDF | Kiss the PDF",
    seoDescription: "Create mutually exclusive radio button field groups.",
    keywords: ["add radio button pdf"],
  },
  {
    id: "add-dropdown",
    name: "Add Dropdown",
    description: "Add select dropdown lists with option items to PDF forms.",
    category: "Forms",
    href: "/add-dropdown",
    icon: "ChevronDown",
    status: "placeholder",
    seoTitle: "Add Dropdown Select Menu to PDF | Kiss the PDF",
    seoDescription: "Insert interactive dropdown select menus into PDF forms.",
    keywords: ["add dropdown pdf", "select menu pdf"],
  },
  {
    id: "add-signature-field",
    name: "Add Signature Field",
    description: "Add a designated digital signature block to a PDF.",
    category: "Forms",
    href: "/add-signature-field",
    icon: "Signature",
    status: "placeholder",
    seoTitle: "Add Signature Field to PDF | Kiss the PDF",
    seoDescription: "Insert interactive digital signature placeholder fields.",
    keywords: ["add signature field pdf", "signature placeholder"],
  },
  {
    id: "add-date-field",
    name: "Add Date Field",
    description: "Add auto-formatted date picker input fields to a PDF.",
    category: "Forms",
    href: "/add-date-field",
    icon: "Calendar",
    status: "placeholder",
    seoTitle: "Add Date Input Field to PDF | Kiss the PDF",
    seoDescription: "Insert formatted date input fields onto form pages.",
    keywords: ["add date field pdf"],
  },
  {
    id: "add-initials",
    name: "Add Initials",
    description: "Add initial boxes or stamp fields to document pages.",
    category: "Forms",
    href: "/add-initials",
    icon: "CaseSensitive",
    status: "placeholder",
    seoTitle: "Add Initials to PDF Document | Kiss the PDF",
    seoDescription: "Insert initial stamps and placeholders for contract sign-offs.",
    keywords: ["add initials pdf"],
  },
  {
    id: "draw-signature",
    name: "Draw Signature",
    description: "Draw your handwritten signature using a digital canvas pad.",
    category: "Forms",
    href: "/draw-signature",
    icon: "PenTool",
    status: "placeholder",
    seoTitle: "Draw Signature on PDF Online | Kiss the PDF",
    seoDescription: "Draw your signature on an interactive pad and place it onto document pages.",
    keywords: ["draw signature pdf", "e-sign pdf"],
  },
  {
    id: "upload-signature",
    name: "Upload Signature",
    description: "Upload an image of your signature and place it on PDF pages.",
    category: "Forms",
    href: "/upload-signature",
    icon: "Upload",
    status: "placeholder",
    seoTitle: "Upload & Place Signature Image on PDF | Kiss the PDF",
    seoDescription: "Upload a signature photo or PNG image and place it onto your PDF.",
    keywords: ["upload signature pdf", "sign pdf image"],
  },
  {
    id: "flatten-pdf-form",
    name: "Flatten PDF Form",
    description: "Flatten interactive form fields into non-editable page graphics.",
    category: "Forms",
    href: "/flatten-pdf-form",
    icon: "Layers",
    status: "placeholder",
    seoTitle: "Flatten PDF Form Fields | Kiss the PDF",
    seoDescription: "Convert interactive form fields into permanent page graphics.",
    keywords: ["flatten pdf form", "lock form fields pdf"],
  },

  // ==========================================
  // Category 7: Enhancement (9 Tools)
  // ==========================================
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add customizable page numbers to top or bottom margins.",
    category: "Enhancement",
    href: "/page-numbers",
    icon: "ListOrdered",
    status: "placeholder",
    seoTitle: "Add Page Numbers to PDF Online | Kiss the PDF",
    seoDescription: "Number PDF pages with custom position, font, and format options.",
    keywords: ["page numbers pdf", "add page numbers to pdf"],
  },
  {
    id: "header-footer",
    name: "Header & Footer",
    description: "Add headers and footers with custom text or page numbers.",
    category: "Enhancement",
    href: "/header-footer",
    icon: "AlignVerticalSpaceAround",
    status: "placeholder",
    seoTitle: "Add Header & Footer to PDF | Kiss the PDF",
    seoDescription: "Add custom text, dates, and page counts to headers and footers.",
    keywords: ["header footer pdf", "add header to pdf"],
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add text or image watermarks across PDF document pages.",
    category: "Enhancement",
    href: "/watermark-pdf",
    icon: "Droplets",
    status: "placeholder",
    seoTitle: "Add Watermark to PDF Online | Kiss the PDF",
    seoDescription: "Stamp custom text or logo image watermarks on PDF pages.",
    keywords: ["watermark pdf", "add watermark to pdf"],
  },
  {
    id: "remove-watermark",
    name: "Remove Watermark",
    description: "Remove text or image watermark layers from PDF pages.",
    category: "Enhancement",
    href: "/remove-watermark",
    icon: "Droplets",
    status: "placeholder",
    seoTitle: "Remove Watermark from PDF | Kiss the PDF",
    seoDescription: "Remove watermark overlay elements from PDF document pages.",
    keywords: ["remove watermark pdf"],
  },
  {
    id: "bookmarks",
    name: "Bookmarks",
    description: "Create outline bookmarks for fast document navigation.",
    category: "Enhancement",
    href: "/bookmarks",
    icon: "Bookmark",
    status: "placeholder",
    seoTitle: "Add Bookmarks to PDF Document | Kiss the PDF",
    seoDescription: "Create outline bookmarks and chapter links in PDF files.",
    keywords: ["pdf bookmarks", "add bookmarks pdf"],
  },
  {
    id: "edit-bookmarks",
    name: "Edit Bookmarks",
    description: "Edit or reorganize existing PDF outline bookmarks.",
    category: "Enhancement",
    href: "/edit-bookmarks",
    icon: "BookmarkPlus",
    status: "placeholder",
    seoTitle: "Edit PDF Bookmarks & Outline | Kiss the PDF",
    seoDescription: "Modify, rename, or delete existing PDF outline bookmarks.",
    keywords: ["edit bookmarks pdf"],
  },
  {
    id: "table-of-contents",
    name: "Table of Contents",
    description: "Generate a hyperlinked Table of Contents page for your PDF.",
    category: "Enhancement",
    href: "/table-of-contents",
    icon: "Table",
    status: "placeholder",
    seoTitle: "Generate PDF Table of Contents | Kiss the PDF",
    seoDescription: "Generate a hyperlinked Table of Contents page from headings.",
    keywords: ["table of contents pdf", "pdf index"],
  },
  {
    id: "add-hyperlinks",
    name: "Add Hyperlinks",
    description: "Add clickable web URLs or internal page jump links to PDF pages.",
    category: "Enhancement",
    href: "/add-hyperlinks",
    icon: "Link",
    status: "placeholder",
    seoTitle: "Add Clickable Hyperlinks to PDF | Kiss the PDF",
    seoDescription: "Add clickable URL links and internal page jump links onto PDF pages.",
    keywords: ["add link to pdf", "hyperlink pdf"],
  },
  {
    id: "extract-links",
    name: "Extract Links",
    description: "Scan and extract all embedded web links and URLs from a PDF.",
    category: "Enhancement",
    href: "/extract-links",
    icon: "ExternalLink",
    status: "placeholder",
    seoTitle: "Extract URLs & Links from PDF | Kiss the PDF",
    seoDescription: "Extract all embedded web hyperlinks from inside a PDF document.",
    keywords: ["extract links pdf", "find urls pdf"],
  },

  // ==========================================
  // Category 8: Reading & Utilities (6 Tools)
  // ==========================================
  {
    id: "add-qr-code",
    name: "Add QR Code",
    description: "Generate and insert scannable QR codes onto PDF pages.",
    category: "Reading",
    href: "/add-qr-code",
    icon: "QrCode",
    status: "placeholder",
    seoTitle: "Add QR Code to PDF Page | Kiss the PDF",
    seoDescription: "Generate scannable QR codes pointing to URLs or text and stamp onto PDF.",
    keywords: ["add qr code to pdf", "stamp qr code"],
  },
  {
    id: "pdf-reader",
    name: "PDF Reader",
    description: "Fast, distraction-free browser PDF viewer with thumbnail navigation.",
    category: "Reading",
    href: "/pdf-reader",
    icon: "BookOpen",
    status: "placeholder",
    seoTitle: "Free Browser PDF Reader | Kiss the PDF",
    seoDescription: "Read PDF files directly in your browser with zoom and thumbnail navigation.",
    keywords: ["pdf reader online", "view pdf browser"],
  },
  {
    id: "fullscreen-pdf",
    name: "Fullscreen PDF",
    description: "Read PDFs in a clean, distraction-free fullscreen presentation mode.",
    category: "Reading",
    href: "/fullscreen-pdf",
    icon: "Maximize",
    status: "placeholder",
    seoTitle: "Fullscreen PDF Viewer | Kiss the PDF",
    seoDescription: "View PDFs in full-screen reader mode.",
    keywords: ["fullscreen pdf", "pdf presentation"],
  },
  {
    id: "pdf-search",
    name: "PDF Search",
    description: "Search and highlight text keywords across all pages of a PDF.",
    category: "Reading",
    href: "/pdf-search",
    icon: "Search",
    status: "placeholder",
    seoTitle: "Search Text Inside PDF Online | Kiss the PDF",
    seoDescription: "Search text keywords across PDF pages with instant match highlighting.",
    keywords: ["search text in pdf", "pdf search tool"],
  },
  {
    id: "pdf-presentation",
    name: "PDF Presentation",
    description: "Present PDF slides in fullscreen with slide controls.",
    category: "Reading",
    href: "/pdf-presentation",
    icon: "MonitorPlay",
    status: "placeholder",
    seoTitle: "PDF Slide Presentation Mode | Kiss the PDF",
    seoDescription: "Present PDF document pages as slides with keyboard presentation controls.",
    keywords: ["pdf presentation", "present pdf slides"],
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality.",
    category: "Reading",
    href: "/compress-pdf",
    icon: "Minimize",
    status: "placeholder",
    seoTitle: "Compress PDF Online for Free | Kiss the PDF",
    seoDescription: "Reduce PDF file size with structural optimization in your browser.",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf"],
  },
];

export const getToolsByCategory = (): Record<string, ToolDefinition[]> => {
  return tools.reduce((acc, tool) => {
    if (!acc[tool.category]) {
      acc[tool.category] = [];
    }
    acc[tool.category].push(tool);
    return acc;
  }, {} as Record<string, ToolDefinition[]>);
};
